In [79]:
import pandas as pd

In [80]:
train = pd.read_csv('twitter_training.csv')

In [81]:
train

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [82]:
## Can work with 15000 samples for faster training

# train.sample(15000, random_state=42)

In [83]:
train.shape

(74681, 4)

In [84]:
train.columns

Index(['2401', 'Borderlands', 'Positive',
       'im getting on borderlands and i will murder you all ,'],
      dtype='object')

In [85]:
train['Positive'].value_counts()

Positive
Negative      22542
Positive      20831
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [86]:
train.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    686
dtype: int64

In [87]:
train.duplicated().sum()

2700

### Data Cleaning

In [88]:
train = train.dropna()

In [89]:
train.isnull().sum()

2401                                                     0
Borderlands                                              0
Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

In [90]:
train.shape

(73995, 4)

In [91]:
train.drop_duplicates(inplace=True)

/tmp/ipykernel_88243/1644190799.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.drop_duplicates(inplace=True)

In [92]:
train.duplicated().sum()

0

In [93]:
train.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [94]:
train.columns

Index(['2401', 'Borderlands', 'Positive',
       'im getting on borderlands and i will murder you all ,'],
      dtype='object')

In [95]:
train.drop(columns=['2401','Borderlands'], inplace=True)

/tmp/ipykernel_88243/1951011165.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.drop(columns=['2401','Borderlands'], inplace=True)

In [96]:
train.rename(
    columns={
        'Positive': 'Sentiment',
        'im getting on borderlands and i will murder you all ,': 'Tweets'
    },
    inplace=True
)

/tmp/ipykernel_88243/1106697295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.rename(

In [97]:
# print(train[train['Sentiment']=='Negative'])

In [98]:
# condition = (train['Sentiment']=='Positive') & (train['Sentiment'] == 'Negative') | (train['Sentiment'] =='Neutral')
# train = train[(train['Sentiment']=='Positive') & (train['Sentiment'] == 'Negative') | (train['Sentiment'] =='Neutral')]

In [99]:
train.head()

  Sentiment                                             Tweets
0  Positive  I am coming to the borders and I will kill you...
1  Positive  im getting on borderlands and i will kill you ...
2  Positive  im coming on borderlands and i will murder you...
3  Positive  im getting on borderlands 2 and i will murder ...
4  Positive  im getting into borderlands and i can murder y...

In [100]:
train['Sentiment'].value_counts()

Sentiment
Negative      21698
Positive      19712
Neutral       17708
Irrelevant    12537
Name: count, dtype: int64

In [101]:
train = train[train['Sentiment'] !='Irrelevant']

In [102]:
train['Sentiment'].value_counts()

Sentiment
Negative    21698
Positive    19712
Neutral     17708
Name: count, dtype: int64

feature Engineering : -> No. of characters, No. or words.

### Feature Encoding

In [103]:
from sklearn.preprocessing import LabelEncoder

In [104]:
le = LabelEncoder()

In [105]:
train['Sentiment'] = le.fit_transform(train['Sentiment'])

In [106]:
train['Sentiment']

0        2
1        2
2        2
3        2
4        2
        ..
74676    2
74677    2
74678    2
74679    2
74680    2
Name: Sentiment, Length: 59118, dtype: int64

In [107]:
train['Sentiment'].value_counts()

Sentiment
0    21698
2    19712
1    17708
Name: count, dtype: int64

In [108]:
from tensorflow import keras

In [109]:
Tokenizer = keras.preprocessing.text.Tokenizer

tokenizer = Tokenizer()

### Here Keras Tokenizer is used to convert text into sequence of numbers. 
when we use tokenizer, it creates a dictionary of all the words in the text and assigns a unique number to each word. Then it converts the text into a sequence of numbers based on the dictionary.

- and also if new word comes in the test data which is not present in the training data, then it uses something called out of vocabulary token (OOV) to represent that word.
- Let's say : Hello, okay. is the training data. 
- Testing : amit --> OOV token --> treating as "Nothing" or "Unknown"

In [110]:
tokenizer = Tokenizer(oov_token="Nothing")

In [111]:
tokenizer.fit_on_texts(train['Tweets'])

In [112]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'and': 5,
 'a': 6,
 'of': 7,
 'is': 8,
 'in': 9,
 'for': 10,
 'it': 11,
 'this': 12,
 'my': 13,
 'on': 14,
 'you': 15,
 'that': 16,
 'com': 17,
 'game': 18,
 'with': 19,
 'so': 20,
 'be': 21,
 'me': 22,
 'have': 23,
 'just': 24,
 'but': 25,
 'not': 26,
 'are': 27,
 'all': 28,
 'was': 29,
 'at': 30,
 'like': 31,
 '2': 32,
 'out': 33,
 'from': 34,
 'your': 35,
 'now': 36,
 'get': 37,
 'pic': 38,
 'twitter': 39,
 'as': 40,
 't': 41,
 'we': 42,
 'play': 43,
 'johnson': 44,
 'they': 45,
 'one': 46,
 'can': 47,
 'do': 48,
 'if': 49,
 'new': 50,
 'good': 51,
 'no': 52,
 'about': 53,
 'an': 54,
 'has': 55,
 'will': 56,
 'really': 57,
 'when': 58,
 'more': 59,
 'up': 60,
 "i'm": 61,
 'what': 62,
 'time': 63,
 'love': 64,
 'unk': 65,
 '3': 66,
 'or': 67,
 'how': 68,
 'why': 69,
 'by': 70,
 'some': 71,
 'co': 72,
 'shit': 73,
 "it's": 74,
 'been': 75,
 'amazon': 76,
 'still': 77,
 'people': 78,
 '’': 79,
 'https': 80,
 'facebook': 81,
 'games': 82,
 'best': 83,
 'microsoft': 84,
 'verizon': 85,
 'playing': 86,
 'got': 87,
 '1': 88,
 'see': 89,
 'xbox': 90,
 'even': 91,
 'dead': 92,
 'great': 93,
 'because': 94,
 'google': 95,
 'rhandlerr': 96,
 'go': 97,
 'fuck': 98,
 'please': 99,
 'fucking': 100,
 'red': 101,
 'back': 102,
 'had': 103,
 'them': 104,
 'us': 105,
 'home': 106,
 'there': 107,
 '5': 108,
 'only': 109,
 'much': 110,
 'who': 111,
 'going': 112,
 'after': 113,
 'am': 114,
 'nvidia': 115,
 'their': 116,
 's': 117,
 'its': 118,
 'fix': 119,
 "can't": 120,
 'borderlands': 121,
 'first': 122,
 'make': 123,
 'over': 124,
 'know': 125,
 'fifa': 126,
 'our': 127,
 'again': 128,
 'would': 129,
 "don't": 130,
 'tv': 131,
 'than': 132,
 'fun': 133,
 'day': 134,
 'these': 135,
 '4': 136,
 '2020': 137,
 'very': 138,
 'eamaddennfl': 139,
 '…': 140,
 'also': 141,
 'most': 142,
 'today': 143,
 'bad': 144,
 'here': 145,
 'ever': 146,
 'want': 147,
 'nba2k': 148,
 'rainbow6game': 149,
 'then': 150,
 'every': 151,
 'wait': 152,
 'pubg': 153,
 'he': 154,
 'redemption': 155,
 'never': 156,
 'thank': 157,
 'x': 158,
 'video': 159,
 'ps5': 160,
 'call': 161,
 'series': 162,
 'world': 163,
 'year': 164,
 '10': 165,
 'depot': 166,
 'twitch': 167,
 'news': 168,
 'gta': 169,
 'right': 170,
 'getting': 171,
 "i've": 172,
 'too': 173,
 'work': 174,
 'off': 175,
 'think': 176,
 'thanks': 177,
 'amazing': 178,
 'played': 179,
 'watch': 180,
 'last': 181,
 'legends': 182,
 'v': 183,
 'any': 184,
 'league': 185,
 'help': 186,
 'well': 187,
 'guys': 188,
 'u': 189,
 'being': 190,
 'into': 191,
 'black': 192,
 'ghostrecon': 193,
 'i’m': 194,
 'down': 195,
 'years': 196,
 'looks': 197,
 'youtu': 198,
 'happy': 199,
 'did': 200,
 'actually': 201,
 'damn': 202,
 'overwatch': 203,
 'warcraft': 204,
 'man': 205,
 'another': 206,
 'youtube': 207,
 'creed': 208,
 'stop': 209,
 'team': 210,
 'next': 211,
 'buy': 212,
 'made': 213,
 'should': 214,
 'live': 215,
 'need': 216,
 'battlefield': 217,
 'everyone': 218,
 'say': 219,
 'duty': 220,
 'always': 221,
 'look': 222,
 'while': 223,
 'finally': 224,
 'via': 225,
 'since': 226,
 'could': 227,
 'big': 228,
 'update': 229,
 'm': 230,
 'which': 231,
 'hearthstone': 232,
 'players': 233,
 'many': 234,
 'csgo': 235,
 'way': 236,
 'better': 237,
 'excited': 238,
 'free': 239,
 'something': 240,
 'it’s': 241,
 'already': 242,
 'same': 243,
 'online': 244,
 'his': 245,
 'were': 246,
 'win': 247,
 'store': 248,
 'nice': 249,
 'money': 250,
 'other': 251,
 'fortnite': 252,
 'thing': 253,
 'come': 254,
 'playstation': 255,
 '20': 256,
 'take': 257,
 'hate': 258,
 'wow': 259,
 '6': 260,
 'playapex': 261,
 'such': 262,
 'days': 263,
 'having': 264,
 'support': 265,
 'give': 266,
 'war': 267,
 'wtf': 268,
 'two': 269,
 'before': 270,
 'awesome': 271,
 'bit': 272,
 'stream': 273,
 'where': 274,
 'ass': 275,
 'keep': 276,
 'care': 277,
 'gonna': 278,
 'trying': 279,
 'servers': 280,
 'ly': 281,
 'pc': 282,
 'lol': 283,
 'done': 284,
 'ubisoft': 285,
 '100': 286,
 'check': 287,
 'does': 288,
 'life': 289,
 'looking': 290,
 'her': 291,
 'access': 292,
 'long': 293,
 'baby': 294,
 'everything': 295,
 'health': 296,
 'someone': 297,
 'old': 298,
 'pretty': 299,
 'through': 300,
 'dota': 301,
 'oh': 302,
 'cool': 303,
 'lot': 304,
 'him': 305,
 'feel': 306,
 'use': 307,
 'doing': 308,
 'super': 309,
 'both': 310,
 'hey': 311,
 'top': 312,
 'nothing': 313,
 'im': 314,
 'card': 315,
 'company': 316,
 'hell': 317,
 'real': 318,
 'uk': 319,
 'account': 320,
 'night': 321,
 'things': 322,
 'mobile': 323,
 'making': 324,
 'cyberpunk': 325,
 'makes': 326,
 'ops': 327,
 'favorite': 328,
 'start': 329,
 'problem': 330,
 'anyone': 331,
 '2077': 332,
 'working': 333,
 'little': 334,
 'until': 335,
 '7': 336,
 'powder': 337,
 'worst': 338,
 'cold': 339,
 'those': 340,
 'try': 341,
 'literally': 342,
 'phone': 343,
 'won': 344,
 'god': 345,
 'service': 346,
 'hours': 347,
 'gaming': 348,
 'italy': 349,
 'probably': 350,
 "that's": 351,
 'ea': 352,
 'let': 353,
 'week': 354,
 'player': 355,
 'almost': 356,
 'story': 357,
 'hard': 358,
 'said': 359,
 'yet': 360,
 'few': 361,
 'hope': 362,
 'season': 363,
 'against': 364,
 'can’t': 365,
 'stupid': 366,
 'times': 367,
 'show': 368,
 'whole': 369,
 'miss': 370,
 'sure': 371,
 'app': 372,
 "doesn't": 373,
 'around': 374,
 'apex': 375,
 'pay': 376,
 'find': 377,
 '19': 378,
 'chance': 379,
 'internet': 380,
 'anything': 381,
 'far': 382,
 '2k': 383,
 'ranked': 384,
 'cant': 385,
 'console': 386,
 'lost': 387,
 'release': 388,
 'end': 389,
 'open': 390,
 '21': 391,
 'part': 392,
 'own': 393,
 'don’t': 394,
 'callofduty': 395,
 'says': 396,
 'friends': 397,
 'stuff': 398,
 'maybe': 399,
 'coming': 400,
 'ban': 401,
 'using': 402,
 'crazy': 403,
 'beautiful': 404,
 'mode': 405,
 'ps4': 406,
 'business': 407,
 'without': 408,
 'full': 409,
 'cs': 410,
 'minutes': 411,
 'absolutely': 412,
 "didn't": 413,
 'guy': 414,
 'trash': 415,
 'thought': 416,
 'order': 417,
 'put': 418,
 'tell': 419,
 'dont': 420,
 'tonight': 421,
 'org': 422,
 'enough': 423,
 "assassin's": 424,
 'enjoy': 425,
 'e': 426,
 'broken': 427,
 'vaccine': 428,
 'd': 429,
 'w': 430,
 'tried': 431,
 'month': 432,
 'madden': 433,
 'tt': 434,
 '0': 435,
 'interesting': 436,
 'gameplay': 437,
 'gets': 438,
 'fact': 439,
 'assassins': 440,
 'used': 441,
 'went': 442,
 'covid': 443,
 'epic': 444,
 'screen': 445,
 'wrong': 446,
 'run': 447,
 '30': 448,
 'point': 449,
 'though': 450,
 'bought': 451,
 'change': 452,
 '12': 453,
 'sad': 454,
 'kill': 455,
 'y’all': 456,
 'perfect': 457,
 'reason': 458,
 "won't": 459,
 'hit': 460,
 'banned': 461,
 'soon': 462,
 'feels': 463,
 '15': 464,
 'line': 465,
 'cod': 466,
 'selling': 467,
 'p': 468,
 'watching': 469,
 'may': 470,
 'worth': 471,
 'cause': 472,
 '9': 473,
 'skin': 474,
 'services': 475,
 'due': 476,
 'net': 477,
 'problems': 478,
 "y'all": 479,
 'launch': 480,
 'system': 481,
 'data': 482,
 'away': 483,
 'price': 484,
 'forward': 485,
 'million': 486,
 'seems': 487,
 'bro': 488,
 'grand': 489,
 'post': 490,
 'myself': 491,
 'i’ve': 492,
 'definitely': 493,
 "you're": 494,
 '8': 495,
 'huge': 496,
 "i'll": 497,
 'high': 498,
 'based': 499,
 'currently': 500,
 'able': 501,
 'playhearthstone': 502,
 'dota2': 503,
 'might': 504,
 'content': 505,
 'read': 506,
 'ago': 507,
 'tomorrow': 508,
 'months': 509,
 'exciting': 510,
 'patch': 511,
 'pro': 512,
 'homedepot': 513,
 'comes': 514,
 'instead': 515,
 'idea': 516,
 'buying': 517,
 'talc': 518,
 'finished': 519,
 'server': 520,
 'job': 521,
 'sorry': 522,
 'terrible': 523,
 'power': 524,
 'experience': 525,
 'needs': 526,
 'graphics': 527,
 'dlvr': 528,
 'match': 529,
 'sucks': 530,
 'morning': 531,
 'half': 532,
 'cards': 533,
 'odyssey': 534,
 'place': 535,
 'windows': 536,
 'else': 537,
 'community': 538,
 'ift': 539,
 'myteam': 540,
 'second': 541,
 'latest': 542,
 'during': 543,
 'character': 544,
 'pre': 545,
 'started': 546,
 'wanted': 547,
 'saying': 548,
 'share': 549,
 'c': 550,
 'seen': 551,
 'music': 552,
 'she': 553,
 'came': 554,
 'earned': 555,
 'event': 556,
 'yes': 557,
 'completely': 558,
 'streaming': 559,
 'once': 560,
 'wanna': 561,
 'must': 562,
 'found': 563,
 'issues': 564,
 'took': 565,
 'ok': 566,
 'rewards': 567,
 'single': 568,
 '”': 569,
 'name': 570,
 'die': 571,
 'trailer': 572,
 'weekend': 573,
 'anymore': 574,
 'achievement': 575,
 'breakpoint': 576,
 'different': 577,
 'mean': 578,
 'honestly': 579,
 'worse': 580,
 'hour': 581,
 'seriously': 582,
 'level': 583,
 'n2k': 584,
 'yo': 585,
 'r': 586,
 'friend': 587,
 'luck': 588,
 'error': 589,
 'gold': 590,
 'hi': 591,
 'running': 592,
 'remember': 593,
 'list': 594,
 'link': 595,
 'guess': 596,
 'holy': 597,
 'points': 598,
 'rtx': 599,
 'easports': 600,
 'issue': 601,
 'annoying': 602,
 'ghost': 603,
 'taken': 604,
 'apple': 605,
 'eu': 606,
 'ready': 607,
 '•': 608,
 'less': 609,
 'later': 610,
 'either': 611,
 'blizzard': 612,
 'fortnitegame': 613,
 'face': 614,
 'tech': 615,
 'page': 616,
 'yall': 617,
 'deal': 618,
 'entire': 619,
 'customer': 620,
 'products': 621,
 'ubisoftsupport': 622,
 'called': 623,
 'switch': 624,
 'set': 625,
 're': 626,
 'proud': 627,
 'shot': 628,
 'fan': 629,
 'major': 630,
 'three': 631,
 'warzone': 632,
 'kind': 633,
 'left': 634,
 'cannot': 635,
 'seeing': 636,
 'kinda': 637,
 'break': 638,
 'person': 639,
 'talk': 640,
 'starting': 641,
 'despite': 642,
 'saw': 643,
 'understand': 644,
 'least': 645,
 'review': 646,
 'death': 647,
 'taking': 648,
 'apps': 649,
 'lmao': 650,
 'pass': 651,
 'move': 652,
 'j': 653,
 'below': 654,
 'ronnie2k': 655,
 'early': 656,
 'hear': 657,
 'incredible': 658,
 'bring': 659,
 'omg': 660,
 'join': 661,
 'india': 662,
 'action': 663,
 'past': 664,
 'sick': 665,
 'house': 666,
 'easy': 667,
 'wikipedia': 668,
 'loved': 669,
 'leagueoflegends': 670,
 'funny': 671,
 'glad': 672,
 'waiting': 673,
 'global': 674,
 'small': 675,
 'sounds': 676,
 'companies': 677,
 'follow': 678,
 'fans': 679,
 'killed': 680,
 'b': 681,
 'battle': 682,
 'final': 683,
 'gift': 684,
 'number': 685,
 'class': 686,
 'weeks': 687,
 'tired': 688,
 'each': 689,
 'birthday': 690,
 'believe': 691,
 'gen': 692,
 'quite': 693,
 'mad': 694,
 'article': 695,
 'happened': 696,
 'delayed': 697,
 '3080': 698,
 'cancer': 699,
 'goes': 700,
 'beluba': 701,
 'fantastic': 702,
 'market': 703,
 'family': 704,
 'add': 705,
 'sometimes': 706,
 'franchise': 707,
 'turn': 708,
 'step': 709,
 "haven't": 710,
 'y': 711,
 'together': 712,
 'heart': 713,
 'updates': 714,
 'o': 715,
 'smh': 716,
 'connection': 717,
 'leave': 718,
 'social': 719,
 'n': 720,
 'history': 721,
 'main': 722,
 'kills': 723,
 'modern': 724,
 'totally': 725,
 "what's": 726,
 'code': 727,
 'version': 728,
 'living': 729,
 'hello': 730,
 'fps': 731,
 'hot': 732,
 'don': 733,
 'moments': 734,
 'movie': 735,
 'design': 736,
 'bullshit': 737,
 'trump': 738,
 'decided': 739,
 'bc': 740,
 'yeah': 741,
 'close': 742,
 'f': 743,
 'ur': 744,
 'yesterday': 745,
 'including': 746,
 'videos': 747,
 'email': 748,
 'characters': 749,
 'mind': 750,
 'speed': 751,
 'gotta': 752,
 'garbage': 753,
 "let's": 754,
 'white': 755,
 'complete': 756,
 'suck': 757,
 '–': 758,
 "we're": 759,
 've': 760,
 "there's": 761,
 'original': 762,
 "they're": 763,
 'truly': 764,
 'teams': 765,
 'retweet': 766,
 'canada': 767,
 'thinking': 768,
 'edition': 769,
 'spend': 770,
 'released': 771,
 'test': 772,
 'between': 773,
 'en': 774,
 'available': 775,
 'talking': 776,
 'sound': 777,
 'sony': 778,
 'gone': 779,
 'especially': 780,
 'wish': 781,
 'current': 782,
 'beta': 783,
 'keeps': 784,
 '11': 785,
 'that’s': 786,
 'technology': 787,
 'gpu': 788,
 'late': 789,
 'told': 790,
 'sold': 791,
 'nba': 792,
 'ridiculous': 793,
 'crap': 794,
 '“': 795,
 'playoverwatch': 796,
 'daily': 797,
 'spent': 798,
 'biggest': 799,
 'moment': 800,
 'absolute': 801,
 'giving': 802,
 'warfare': 803,
 'search': 804,
 'true': 805,
 'instagram': 806,
 'stay': 807,
 'massive': 808,
 'within': 809,
 'performance': 810,
 'book': 811,
 'item': 812,
 'map': 813,
 'under': 814,
 'longer': 815,
 'low': 816,
 'sell': 817,
 'fast': 818,
 'welcome': 819,
 'lose': 820,
 'car': 821,
 'drop': 822,
 'star': 823,
 '24': 824,
 'pls': 825,
 'works': 826,
 'controller': 827,
 'commission': 828,
 'customers': 829,
 'nfl': 830,
 'mut': 831,
 'bitch': 832,
 'report': 833,
 'toxic': 834,
 'hyped': 835,
 '99': 836,
 'stock': 837,
 'fire': 838,
 'okay': 839,
 'geforce': 840,
 'greatest': 841,
 'stuck': 842,
 'clips': 843,
 'ordered': 844,
 'unit': 845,
 'shows': 846,
 'feeling': 847,
 'city': 848,
 '50': 849,
 'special': 850,
 'behind': 851,
 'date': 852,
 'means': 853,
 'men': 854,
 'insane': 855,
 'killing': 856,
 'coronavirus': 857,
 'cute': 858,
 'plays': 859,
 'eahelp': 860,
 'side': 861,
 'plus': 862,
 'congratulations': 863,
 'media': 864,
 'activision': 865,
 'prime': 866,
 'tweet': 867,
 'hero': 868,
 'bugs': 869,
 'stopped': 870,
 'campaign': 871,
 'official': 872,
 'digital': 873,
 'ai': 874,
 'valhalla': 875,
 'enjoyed': 876,
 'save': 877,
 'alone': 878,
 'tho': 879,
 'worked': 880,
 'trust': 881,
 'box': 882,
 'iphone': 883,
 'trial': 884,
 'rockstargames': 885,
 'future': 886,
 'wants': 887,
 'dlc': 888,
 'dude': 889,
 'received': 890,
 'website': 891,
 'happens': 892,
 'bug': 893,
 'girl': 894,
 'changes': 895,
 'cyberpunkgame': 896,
 'become': 897,
 'losing': 898,
 'joke': 899,
 'dear': 900,
 'computer': 901,
 'product': 902,
 'seem': 903,
 'imagine': 904,
 'sales': 905,
 'g': 906,
 'control': 907,
 'slow': 908,
 '25': 909,
 'wins': 910,
 'platform': 911,
 'head': 912,
 'dark': 913,
 'drive': 914,
 'takes': 915,
 'information': 916,
 'recon': 917,
 'powerful': 918,
 'download': 919,
 'simply': 920,
 '14': 921,
 'pick': 922,
 'network': 923,
 'rt': 924,
 'racist': 925,
 'loving': 926,
 'safe': 927,
 'somehow': 928,
 "isn't": 929,
 'quality': 930,
 'word': 931,
 'heard': 932,
 'continue': 933,
 'channel': 934,
 'log': 935,
 'crashing': 936,
 'yourself': 937,
 'boring': 938,
 'poverty': 939,
 'fight': 940,
 'broke': 941,
 'forever': 942,
 'dog': 943,
 'l': 944,
 'kids': 945,
 'hold': 946,
 'cuz': 947,
 'stores': 948,
 '60': 949,
 'fake': 950,
 'summoners': 951,
 'felt': 952,
 'boy': 953,
 'appreciate': 954,
 'created': 955,
 'disappointed': 956,
 'users': 957,
 '000': 958,
 'gamer': 959,
 'classic': 960,
 'random': 961,
 'articles': 962,
 'siege': 963,
 'important': 964,
 'rest': 965,
 'sense': 966,
 'buff': 967,
 'shitty': 968,
 'possible': 969,
 "i'd": 970,
 'shut': 971,
 'matter': 972,
 'dying': 973,
 'skins': 974,
 'developers': 975,
 'finish': 976,
 'quit': 977,
 'mask': 978,
 'forgot': 979,
 'wild': 980,
 'sale': 981,
 'missing': 982,
 'esports': 983,
 'row': 984,
 'enjoying': 985,
 'art': 986,
 'brand': 987,
 'paid': 988,
 'twice': 989,
 'gave': 990,
 'sea': 991,
 'auto': 992,
 'valve': 993,
 'others': 994,
 'shooting': 995,
 'learn': 996,
 'fine': 997,
 'plan': 998,
 'golden': 999,
 'wonder': 1000,
 ...}

In [113]:
tokenizer.word_counts

OrderedDict([('i', 24421),
             ('am', 1517),
             ('coming', 403),
             ('to', 23771),
             ('the', 36098),
             ('borders', 11),
             ('and', 21712),
             ('will', 2684),
             ('kill', 348),
             ('you', 9359),
             ('all', 4492),
             ('im', 547),
             ('getting', 1046),
             ('on', 9756),
             ('borderlands', 1412),
             ('murder', 67),
             ('2', 3716),
             ('me', 5527),
             ('into', 947),
             ('can', 2904),
             ('so', 6410),
             ('spent', 179),
             ('a', 19236),
             ('few', 467),
             ('hours', 481),
             ('making', 527),
             ('something', 752),
             ('for', 12494),
             ('fun', 1329),
             ('if', 2857),
             ("don't", 1337),
             ('know', 1391),
             ('huge', 310),
             ('fan', 228),
             ('maya', 22),
             ('is', 14446),
             ('one', 2923),
             ('of', 15616),
             ('my', 9798),
             ('favorite', 517),
             ('characters', 192),
             ('decided', 194),
             ('make', 1400),
             ('myself', 313),
             ('wallpaper', 14),
             ('pc', 624),
             ('here', 1236),
             ('original', 188),
             ('image', 54),
             ('versus', 13),
             ('creation', 6),
             ('made', 847),
             ('enjoy', 376),
             ('pic', 3316),
             ('twitter', 3168),
             ('com', 7756),
             ('mlsi5wf9jg', 4),
             ('couple', 132),
             ('doing', 561),
             ('that', 8272),
             ("i'm", 2536),
             ("here's", 108),
             ('picture', 83),
             ('compared', 63),
             ('have', 5503),
             ('rhandlerr', 1718),
             ('2010', 60),
             ('was', 4382),
             ('rock', 69),
             ('hard', 472),
             ('la', 71),
             ('varlope', 4),
             ('rare', 33),
             ('powerful', 147),
             ('handsome', 69),
             ('jackpot', 9),
             ('3', 2470),
             ('xbox', 1783),
             ('dlvr', 291),
             ('it', 11951),
             ('rmtrgf', 6),
             ('dfr', 7),
             ('vita', 12),
             ('but', 5203),
             ('1', 1832),
             ('live', 832),
             ('music', 274),
             ('sega', 26),
             ('from', 3563),
             ('e', 376),
             ('like', 3851),
             ('london', 21),
             ('de', 99),
             ('2011', 45),
             ('first', 1406),
             ('session', 73),
             ('in', 12740),
             ('long', 594),
             ('time', 2512),
             ('where', 640),
             ('actually', 900),
             ('had', 1611),
             ('really', 2683),
             ('satisfying', 48),
             ('combat', 59),
             ('experience', 294),
             ('got', 1842),
             ('some', 2323),
             ('good', 2821),
             ('kills', 199),
             ('this', 11771),
             ('fighting', 59),
             ('enjoyed', 159),
             ('rather', 123),
             ('real', 539),
             ('nice', 722),
             ('wait', 1154),
             ('hot', 196),
             ('row', 136),
             ('bad', 1237),
             ('did', 905),
             ('biggest', 179),
             ('dissappoinment', 4),
             ('life', 606),
             ('came', 273),
             ('out', 3596),
             ('year', 1090),
             ('ago', 301),
             ('fuck', 1695),
             ('disappointment', 62),
             ('male', 17),
             ('hanging', 62),
             ('back', 1613),
             ('last', 1010),
             ('we', 3056),
             ('finished', 296),
             ('finally', 798),
             ('yas', 10),
             ('thank', 1135),
             ('everyone', 822),
             ('try', 492),
             ('stream', 644),
             ('tomorrow', 301),
             ('not', 5197),
             ('might', 302),
             ('irl', 44),
             ('streams', 57),
             ('while', 799),
             ('awayu', 4),
             ('shall', 40),
             ('see', 1801),
             ('much', 1548),
             ('raids', 29),
             ('mompou', 6),
             ('mumpow', 6),
             ('megamagwitch', 4),
             ('kfdmitch', 3),
             ('find', 439),
             ('yes', 271),
             ("i'll", 310),
             ('maybe', 404),
             ("we'll", 56),
             ('thanks', 1032),
             ('up', 2558),
             ('get', 3415),
             ('haircut', 8),
             ("wasn't", 82),
             ('would', 1344),
             ('still', 2121),
             ('be', 5678),
             ('hawaii', 3),
             ('megamagwife', 1),
             ('fendmitch', 1),
             ('update', 775),
             ('guys', 968),
             ('even', 1776),
             ('go', 1711),
             ('hope', 467),
             ('10', 1088),
             ('never', 1138),
             ('both', 554),
             ('or', 2447),
             ('4', 1302),
             ('hey', 554),
             ('use', 564),
             ('how', 2397),
             ('many', 765),
             ('their', 1484),
             ('man', 886),
             ('gearbox', 30),
             ('needs', 292),
             ('fix', 1448),
             ('dissapointing', 3),
             ('drops', 94),
             ('new', 2850),
             ('dlc', 156),
             ('cant', 416),
             ('fine', 134),
             ('farm', 24),
             ('bosses', 16),
             ('mayhem', 64),
             ('legendary', 124),
             ('drop', 172),
             ('anywhere', 103),
             ('else', 285),
             ('6', 670),
             ('sucks', 290),
             ('alot', 31),
             ('these', 1304),
             ('disappointing', 82),
             ('elsewhere', 13),
             ('disssapointing', 1),
             ('bethesda', 32),
             ('completely', 271),
             ('days', 660),
             ('having', 657),
             ('foot', 38),
             ('unk', 2483),
             ('force', 96),
             ('check', 611),
             ('epic', 360),
             ('streamer', 44),
             ('watch', 1013),
             ('striptease', 2),
             ('our', 1372),
             ('big', 783),
             ('blaming', 8),
             ('sight', 22),
             ('tardiness', 2),
             ('little', 502),
             ('bit', 647),
             ('called', 231),
             ('early', 220),
             ('work', 1043),
             ("can't", 1430),
             ('sorry', 295),
             ('loves', 47),
             ('twitch', 1067),
             ('tv', 1335),
             ('punnisenpai', 3),
             ('borderland', 12),
             ('morning', 290),
             ('catch', 52),
             ('love', 2491),
             ('guilty', 34),
             ('sobriety', 1),
             ('borderline', 5),
             ('why', 2397),
             ('does', 610),
             ('every', 1155),
             ('slicked', 4),
             ('hair', 105),
             ('haven’t', 93),
             ('heard', 144),
             ('bangs', 5),
             ('stupid', 461),
             ('assholes', 43),
             ('border', 39),
             ('countries', 22),
             ('your', 3531),
             ('fallen', 27),
             ('off', 1043),
             ('are', 4800),
             ('aliens', 22),
             ('beth', 9),
             ('she', 274),
             ('haven', 42),
             ('’', 2020),
             ('t', 3070),
             ('enough', 381),
             ('gray', 11),
             ('practically', 16),
             ('france', 4),
             ('greedy', 43),
             ('45', 41),
             ('what', 2520),
             ('going', 1538),
             ('finish', 137),
             ('today', 1243),
             ("i've", 1045),
             ('commands', 25),
             ('set', 229),
             ('looking', 605),
             ('forward', 316),
             ('starting', 224),
             ('about', 2806),
             ('hour', 254),
             ('start', 515),
             ('an', 2718),
             ('installed', 75),
             ('events', 87),
             ('look', 802),
             ('20', 686),
             ('cleaning', 9),
             ('just', 5474),
             ('her', 595),
             ('volume', 20),
             ('awesome', 650),
             ('server', 296),
             ('imma', 55),
             ('probably', 480),
             ('play', 3029),
             ('tps', 11),
             ("that'll", 14),
             ('playing', 1864),
             ("it's", 2190),
             ("that'yer", 1),
             ('ll', 88),
             ('video', 1115),
             ('own', 408),
             ('profzeroo', 5),
             ('w', 371),
             ('3‼', 2),
             ('him', 565),
             ('buff', 138),
             ('ly', 627),
             ('2wmmip5', 6),
             ('say', 816),
             ('shouts', 19),
             ('chat', 113),
             ('chance', 437),
             ('shout', 86),
             ('upcoming', 62),
             ('profzero', 1),
             ('p', 336),
             ('–', 190),
             ('also', 1258),
             ('shows', 166),
             ('via', 797),
             ('at', 4346),
             ('officially', 79),
             ('series', 1091),
             ('its', 1456),
             ('movies', 35),
             ('invitation', 8),
             ('invites', 2),
             ('yessssssss', 4),
             ('fick', 5),
             ('yessssss', 2),
             ('hate', 676),
             ('easy', 216),
             ('modifier', 11),
             ('event', 272),
             ('won’t', 112),
             ('forever', 143),
             ('most', 1245),
             ('i’ve', 313),
             ('game', 7337),
             ('since', 795),
             ('they', 2929),
             ('added', 113),
             ('them', 1591),
             ('horrible', 95),
             ('modifiers', 22),
             ('please', 1669),
             ('give', 655),
             ('option', 129),
             ('turn', 204),
             ('pls', 171),
             ('simple', 119),
             ('chaos', 40),
             ("won't", 344),
             ("that's", 480),
             ('terrible', 295),
             ('saying', 277),
             ('day', 1318),
             ('9', 331),
             ('ability', 43),
             ('thinking', 187),
             ('total', 109),
             ('won', 488),
             ('absolutely', 393),
             ('ridiculous', 181),
             ('ve', 189),
             ('almost', 477),
             ('do', 2891),
             ('best', 1918),
             ('taken', 244),
             ('past', 217),
             ('until', 501),
             ('send', 100),
             ('grounded', 5),
             ('looked', 110),
             ('pretty', 575),
             ('cool', 568),
             ('despite', 224),
             ('tier', 64),
             ('unfunny', 6),
             ('writing', 68),
             ('became', 78),
             ('yet', 470),
             ('another', 883),
             ('survival', 19),
             ('crafting', 5),
             ('can’t', 465),
             ('shitty', 138),
             ('trend', 37),
             ('die', 262),
             ('crappy', 43),
             ('grosskreutz', 1),
             ('spelling', 12),
             ('turned', 115),
             ('crap', 181),
             ('mod', 18),
             ('deep', 72),
             ('fifth', 16),
             ('format', 23),
             ('ultimately', 7),
             ('mobile', 529),
             ('top', 554),
             ('annoying', 245),
             ('seriously', 254),
             ('submit', 29),
             ('complaint', 29),
             ('ceo', 35),
             ("isn't", 145),
             ('paying', 95),
             ('his', 732),
             ('staff', 77),
             ('bonuses', 20),
             ('file', 79),
             ("doesn't", 446),
             ('pay', 440),
             ('employees', 128),
             ('competitors', 16),
             ('suppose', 23),
             ("isn'ain", 1),
             ('entire', 232),
             ('now', 3489),
             ('any', 988),
             ('offering', 27),
             ('fuckin', 100),
             ('trash', 387),
             ('damn', 900),
             ('rubbish', 19),
             ('fucking', 1661),
             ('thrash', 40),
             ('shit', 2220),
             ('35', 58),
             ('played', 1016),
             ('through', 574),
             ('actual', 129),
             ('great', 1769),
             ('guns', 54),
             ('feel', 565),
             ('once', 270),
             ('felt', 141),
             ('needed', 112),
             ('grind', 70),
             ('story', 476),
             ('other', 718),
             ('hand', 118),
             ('very', 1289),
             ('eventual', 5),
             ('cutscene', 15),
             ('skip', 18),
             ('by', 2342),
             ('weapons', 85),
             ('funny', 215),
             ('sequence', 7),
             ('occasional', 2),
             ('slip', 7),
             ('open', 411),
             ('someone', 581),
             ('side', 162),
             ('endless', 29),
             ('5', 1571),
             ('were', 731),
             ('sure', 449),
             ('oh', 569),
             ("yes'm", 1),
             ('extended', 21),
             ('come', 712),
             ('meet', 92),
             ('lovely', 73),
             ('gaming', 481),
             ('goddesses', 5),
             ('gambling', 23),
             ('beautiful', 399),
             ('gods', 33),
             ('16', 128),
             ('green', 67),
             ('bitch', 169),
             ('slut', 10),
             ('miracle', 27),
             ('ok', 266),
             ('loving', 146),
             ('bombs', 18),
             ('over', 1396),
             ('baghdad', 4),
             ('anything', 424),
             ('gets', 367),
             ('hype', 85),
             ('concept', 59),
             ('a1', 9),
             ('gives', 120),
             ('baghad', 1),
             ('seeing', 225),
             ('take', 685),
             ('sir', 64),
             ('case', 117),
             ('earth', 51),
             ('rpg', 40),
             ('uninstalled', 42),
             ('games', 1946),
             ('space', 85),
             ('uninstall', 17),
             ('room', 118),
             ('deleted', 114),
             ('watching', 335),
             ('already', 749),
             ('bleeding', 17),
             ('edge', 133),
             ('clever', 16),
             ('cross', 96),
             ('between', 185),
             ('overwatch', 891),
             ('domination', 9),
             ('mode', 398),
             ('as', 3099),
             ('crossroads', 1),
             ('future', 157),
             ('2016', 95),
             ('fantasy', 111),
             ('non', 78),
             ('bioshock', 25),
             ('switch', 230),
             ('count', 53),
             ('desert', 13),
             ('montana', 1),
             ('after', 1521),
             ('platinum', 48),
             ('loot', 112),
             ('booty', 15),
             ('lot', 567),
             ('has', 2715),
             ('named', 39),
             ('reason', 345),
             ('laptop', 100),
             ('run', 355),
             ('war', 655),
             ('thunder', 23),
             ('warframe', 5),
             ('high', 310),
             ('settings', 75),
             ('moment', 179),
             ('launch', 321),
             ('csgo', 765),
             ('computer', 151),
             ('crashes', 130),
             ('whole', 451),
             ('breaks', 32),
             ('down', 933),
             ('firefox', 36),
             ('plus', 162),
             ('no', 2810),
             ('easily', 72),
             ('currently', 307),
             ('dare', 23),
             ('mind', 192),
             ('software', 127),
             ('mount', 49),
             ('act', 72),
             ('king', 100),
             ('speeds', 54),
             ('jumping', 51),
             ('more', 2563),
             ('dlcs', 13),
             ('vibing', 3),
             ('playlists', 15),
             ('vibe', 28),
             ('dropping', 73),
             ('quality', 145),
             ('720p', 4),
             ('makes', 521),
             ('difference', 57),
             ('well', 972),
             ('runs', 105),
             ('dumb', 131),
             ('internet', 433),
             ('lmao', 222),
             ('heyitscece', 3),
             ('streaming', 271),
             ('vibrating', 1),
             ('lowering', 5),
             ('jon', 20),
             ('downloading', 49),
             ('tumb', 2),
             ('enter', 101),
             ('gunner', 12),
             ('seat', 20),
             ('fear', 68),
             ('step', 204),
             ('trench', 1),
             ('then', 1160),
             ('wav1bacr5j', 4),
             ('wikipedia', 216),
             ('org', 382),
             ('v', 1007),
             ('omg', 219),
             ('ever', 1230),
             ('thwarted', 4),
             ('bank', 78),
             ('foiled', 1),
             ('threatened', 14),
             ('who', 1544),
             ('late', 182),
             ('trip', 43),
             ('seems', 315),
             ('broken', 376),
             ('with', 7195),
             ('m10', 6),
             ('rates', 18),
             ('constantly', 83),
             ('less', 236),
             ('than', 1331),
             ('lower', 87),
             ('levels', 43),
             ('possible', 138),
             ('2500', 9),
             ('swear', 96),
             ('greens', 5),
             ('blues', 23),
             ('boss', 75),
             ('falling', 53),
             ('when', 2618),
             ('rate', 83),
             ('production', 57),
             ('kinda', 225),
             ('pushing', 37),
             ('normal', 85),
             ('people', 2110),
             ('moving', 75),
             ('recovery', 41),
             ('fast', 173),
             ('next', 854),
             ('gold', 251),
             ('amounts', 12),
             ('worked', 158),
             ('polycule', 4),
             ('tonight', 384),
             ('magical', 23),
             ('evening', 61),
             ('end', 413),
             ('sigh', 27),
             ('allowed', 45),
             ('polyphony', 1),
             ('polyslice', 1),
             ('better', 758),
             ('part', 410),
             ('same', 745),
             ('jackson', 50),
             ('happy', 909),
             ('profit', 40),
             ('wise', 27),
             ('expected', 68),
             ('due', 326),
             ('budget', 32),
             ('realize', 74),
             ('because', 1753),
             ('busted', 29),
             ('again', 1352),
             ('only', 1567),
             ('marketing', 87),
             ('business', 396),
             ('prior', 3),
             ('problem', 507),
             ('far', 424),
             ('always', 807),
             ('fav', 49),
             ('certainly', 97),
             ('guardian', 24),
             ('around', 444),
             ('weekend', 260),
             ('managed', 75),
             ('done', 621),
             ('enjoying', 136),
             ('loved', 216),
             ('slutty', 5),
             ('mechanic', 29),
             ('slutsky', 1),
             ('old', 579),
             ('night', 532),
             ('heeps', 4),
             ("we're", 190),
             ('closer', 31),
             ('towards', 102),
             ('raided', 16),

In [114]:
tokenizer.document_count

59118

In [115]:
len((tokenizer.word_index)) ## Vocabulary size

29229

In [116]:
tokenizer.word_counts

OrderedDict([('i', 24421),
             ('am', 1517),
             ('coming', 403),
             ('to', 23771),
             ('the', 36098),
             ('borders', 11),
             ('and', 21712),
             ('will', 2684),
             ('kill', 348),
             ('you', 9359),
             ('all', 4492),
             ('im', 547),
             ('getting', 1046),
             ('on', 9756),
             ('borderlands', 1412),
             ('murder', 67),
             ('2', 3716),
             ('me', 5527),
             ('into', 947),
             ('can', 2904),
             ('so', 6410),
             ('spent', 179),
             ('a', 19236),
             ('few', 467),
             ('hours', 481),
             ('making', 527),
             ('something', 752),
             ('for', 12494),
             ('fun', 1329),
             ('if', 2857),
             ("don't", 1337),
             ('know', 1391),
             ('huge', 310),
             ('fan', 228),
             ('maya', 22),
             ('is', 14446),
             ('one', 2923),
             ('of', 15616),
             ('my', 9798),
             ('favorite', 517),
             ('characters', 192),
             ('decided', 194),
             ('make', 1400),
             ('myself', 313),
             ('wallpaper', 14),
             ('pc', 624),
             ('here', 1236),
             ('original', 188),
             ('image', 54),
             ('versus', 13),
             ('creation', 6),
             ('made', 847),
             ('enjoy', 376),
             ('pic', 3316),
             ('twitter', 3168),
             ('com', 7756),
             ('mlsi5wf9jg', 4),
             ('couple', 132),
             ('doing', 561),
             ('that', 8272),
             ("i'm", 2536),
             ("here's", 108),
             ('picture', 83),
             ('compared', 63),
             ('have', 5503),
             ('rhandlerr', 1718),
             ('2010', 60),
             ('was', 4382),
             ('rock', 69),
             ('hard', 472),
             ('la', 71),
             ('varlope', 4),
             ('rare', 33),
             ('powerful', 147),
             ('handsome', 69),
             ('jackpot', 9),
             ('3', 2470),
             ('xbox', 1783),
             ('dlvr', 291),
             ('it', 11951),
             ('rmtrgf', 6),
             ('dfr', 7),
             ('vita', 12),
             ('but', 5203),
             ('1', 1832),
             ('live', 832),
             ('music', 274),
             ('sega', 26),
             ('from', 3563),
             ('e', 376),
             ('like', 3851),
             ('london', 21),
             ('de', 99),
             ('2011', 45),
             ('first', 1406),
             ('session', 73),
             ('in', 12740),
             ('long', 594),
             ('time', 2512),
             ('where', 640),
             ('actually', 900),
             ('had', 1611),
             ('really', 2683),
             ('satisfying', 48),
             ('combat', 59),
             ('experience', 294),
             ('got', 1842),
             ('some', 2323),
             ('good', 2821),
             ('kills', 199),
             ('this', 11771),
             ('fighting', 59),
             ('enjoyed', 159),
             ('rather', 123),
             ('real', 539),
             ('nice', 722),
             ('wait', 1154),
             ('hot', 196),
             ('row', 136),
             ('bad', 1237),
             ('did', 905),
             ('biggest', 179),
             ('dissappoinment', 4),
             ('life', 606),
             ('came', 273),
             ('out', 3596),
             ('year', 1090),
             ('ago', 301),
             ('fuck', 1695),
             ('disappointment', 62),
             ('male', 17),
             ('hanging', 62),
             ('back', 1613),
             ('last', 1010),
             ('we', 3056),
             ('finished', 296),
             ('finally', 798),
             ('yas', 10),
             ('thank', 1135),
             ('everyone', 822),
             ('try', 492),
             ('stream', 644),
             ('tomorrow', 301),
             ('not', 5197),
             ('might', 302),
             ('irl', 44),
             ('streams', 57),
             ('while', 799),
             ('awayu', 4),
             ('shall', 40),
             ('see', 1801),
             ('much', 1548),
             ('raids', 29),
             ('mompou', 6),
             ('mumpow', 6),
             ('megamagwitch', 4),
             ('kfdmitch', 3),
             ('find', 439),
             ('yes', 271),
             ("i'll", 310),
             ('maybe', 404),
             ("we'll", 56),
             ('thanks', 1032),
             ('up', 2558),
             ('get', 3415),
             ('haircut', 8),
             ("wasn't", 82),
             ('would', 1344),
             ('still', 2121),
             ('be', 5678),
             ('hawaii', 3),
             ('megamagwife', 1),
             ('fendmitch', 1),
             ('update', 775),
             ('guys', 968),
             ('even', 1776),
             ('go', 1711),
             ('hope', 467),
             ('10', 1088),
             ('never', 1138),
             ('both', 554),
             ('or', 2447),
             ('4', 1302),
             ('hey', 554),
             ('use', 564),
             ('how', 2397),
             ('many', 765),
             ('their', 1484),
             ('man', 886),
             ('gearbox', 30),
             ('needs', 292),
             ('fix', 1448),
             ('dissapointing', 3),
             ('drops', 94),
             ('new', 2850),
             ('dlc', 156),
             ('cant', 416),
             ('fine', 134),
             ('farm', 24),
             ('bosses', 16),
             ('mayhem', 64),
             ('legendary', 124),
             ('drop', 172),
             ('anywhere', 103),
             ('else', 285),
             ('6', 670),
             ('sucks', 290),
             ('alot', 31),
             ('these', 1304),
             ('disappointing', 82),
             ('elsewhere', 13),
             ('disssapointing', 1),
             ('bethesda', 32),
             ('completely', 271),
             ('days', 660),
             ('having', 657),
             ('foot', 38),
             ('unk', 2483),
             ('force', 96),
             ('check', 611),
             ('epic', 360),
             ('streamer', 44),
             ('watch', 1013),
             ('striptease', 2),
             ('our', 1372),
             ('big', 783),
             ('blaming', 8),
             ('sight', 22),
             ('tardiness', 2),
             ('little', 502),
             ('bit', 647),
             ('called', 231),
             ('early', 220),
             ('work', 1043),
             ("can't", 1430),
             ('sorry', 295),
             ('loves', 47),
             ('twitch', 1067),
             ('tv', 1335),
             ('punnisenpai', 3),
             ('borderland', 12),
             ('morning', 290),
             ('catch', 52),
             ('love', 2491),
             ('guilty', 34),
             ('sobriety', 1),
             ('borderline', 5),
             ('why', 2397),
             ('does', 610),
             ('every', 1155),
             ('slicked', 4),
             ('hair', 105),
             ('haven’t', 93),
             ('heard', 144),
             ('bangs', 5),
             ('stupid', 461),
             ('assholes', 43),
             ('border', 39),
             ('countries', 22),
             ('your', 3531),
             ('fallen', 27),
             ('off', 1043),
             ('are', 4800),
             ('aliens', 22),
             ('beth', 9),
             ('she', 274),
             ('haven', 42),
             ('’', 2020),
             ('t', 3070),
             ('enough', 381),
             ('gray', 11),
             ('practically', 16),
             ('france', 4),
             ('greedy', 43),
             ('45', 41),
             ('what', 2520),
             ('going', 1538),
             ('finish', 137),
             ('today', 1243),
             ("i've", 1045),
             ('commands', 25),
             ('set', 229),
             ('looking', 605),
             ('forward', 316),
             ('starting', 224),
             ('about', 2806),
             ('hour', 254),
             ('start', 515),
             ('an', 2718),
             ('installed', 75),
             ('events', 87),
             ('look', 802),
             ('20', 686),
             ('cleaning', 9),
             ('just', 5474),
             ('her', 595),
             ('volume', 20),
             ('awesome', 650),
             ('server', 296),
             ('imma', 55),
             ('probably', 480),
             ('play', 3029),
             ('tps', 11),
             ("that'll", 14),
             ('playing', 1864),
             ("it's", 2190),
             ("that'yer", 1),
             ('ll', 88),
             ('video', 1115),
             ('own', 408),
             ('profzeroo', 5),
             ('w', 371),
             ('3‼', 2),
             ('him', 565),
             ('buff', 138),
             ('ly', 627),
             ('2wmmip5', 6),
             ('say', 816),
             ('shouts', 19),
             ('chat', 113),
             ('chance', 437),
             ('shout', 86),
             ('upcoming', 62),
             ('profzero', 1),
             ('p', 336),
             ('–', 190),
             ('also', 1258),
             ('shows', 166),
             ('via', 797),
             ('at', 4346),
             ('officially', 79),
             ('series', 1091),
             ('its', 1456),
             ('movies', 35),
             ('invitation', 8),
             ('invites', 2),
             ('yessssssss', 4),
             ('fick', 5),
             ('yessssss', 2),
             ('hate', 676),
             ('easy', 216),
             ('modifier', 11),
             ('event', 272),
             ('won’t', 112),
             ('forever', 143),
             ('most', 1245),
             ('i’ve', 313),
             ('game', 7337),
             ('since', 795),
             ('they', 2929),
             ('added', 113),
             ('them', 1591),
             ('horrible', 95),
             ('modifiers', 22),
             ('please', 1669),
             ('give', 655),
             ('option', 129),
             ('turn', 204),
             ('pls', 171),
             ('simple', 119),
             ('chaos', 40),
             ("won't", 344),
             ("that's", 480),
             ('terrible', 295),
             ('saying', 277),
             ('day', 1318),
             ('9', 331),
             ('ability', 43),
             ('thinking', 187),
             ('total', 109),
             ('won', 488),
             ('absolutely', 393),
             ('ridiculous', 181),
             ('ve', 189),
             ('almost', 477),
             ('do', 2891),
             ('best', 1918),
             ('taken', 244),
             ('past', 217),
             ('until', 501),
             ('send', 100),
             ('grounded', 5),
             ('looked', 110),
             ('pretty', 575),
             ('cool', 568),
             ('despite', 224),
             ('tier', 64),
             ('unfunny', 6),
             ('writing', 68),
             ('became', 78),
             ('yet', 470),
             ('another', 883),
             ('survival', 19),
             ('crafting', 5),
             ('can’t', 465),
             ('shitty', 138),
             ('trend', 37),
             ('die', 262),
             ('crappy', 43),
             ('grosskreutz', 1),
             ('spelling', 12),
             ('turned', 115),
             ('crap', 181),
             ('mod', 18),
             ('deep', 72),
             ('fifth', 16),
             ('format', 23),
             ('ultimately', 7),
             ('mobile', 529),
             ('top', 554),
             ('annoying', 245),
             ('seriously', 254),
             ('submit', 29),
             ('complaint', 29),
             ('ceo', 35),
             ("isn't", 145),
             ('paying', 95),
             ('his', 732),
             ('staff', 77),
             ('bonuses', 20),
             ('file', 79),
             ("doesn't", 446),
             ('pay', 440),
             ('employees', 128),
             ('competitors', 16),
             ('suppose', 23),
             ("isn'ain", 1),
             ('entire', 232),
             ('now', 3489),
             ('any', 988),
             ('offering', 27),
             ('fuckin', 100),
             ('trash', 387),
             ('damn', 900),
             ('rubbish', 19),
             ('fucking', 1661),
             ('thrash', 40),
             ('shit', 2220),
             ('35', 58),
             ('played', 1016),
             ('through', 574),
             ('actual', 129),
             ('great', 1769),
             ('guns', 54),
             ('feel', 565),
             ('once', 270),
             ('felt', 141),
             ('needed', 112),
             ('grind', 70),
             ('story', 476),
             ('other', 718),
             ('hand', 118),
             ('very', 1289),
             ('eventual', 5),
             ('cutscene', 15),
             ('skip', 18),
             ('by', 2342),
             ('weapons', 85),
             ('funny', 215),
             ('sequence', 7),
             ('occasional', 2),
             ('slip', 7),
             ('open', 411),
             ('someone', 581),
             ('side', 162),
             ('endless', 29),
             ('5', 1571),
             ('were', 731),
             ('sure', 449),
             ('oh', 569),
             ("yes'm", 1),
             ('extended', 21),
             ('come', 712),
             ('meet', 92),
             ('lovely', 73),
             ('gaming', 481),
             ('goddesses', 5),
             ('gambling', 23),
             ('beautiful', 399),
             ('gods', 33),
             ('16', 128),
             ('green', 67),
             ('bitch', 169),
             ('slut', 10),
             ('miracle', 27),
             ('ok', 266),
             ('loving', 146),
             ('bombs', 18),
             ('over', 1396),
             ('baghdad', 4),
             ('anything', 424),
             ('gets', 367),
             ('hype', 85),
             ('concept', 59),
             ('a1', 9),
             ('gives', 120),
             ('baghad', 1),
             ('seeing', 225),
             ('take', 685),
             ('sir', 64),
             ('case', 117),
             ('earth', 51),
             ('rpg', 40),
             ('uninstalled', 42),
             ('games', 1946),
             ('space', 85),
             ('uninstall', 17),
             ('room', 118),
             ('deleted', 114),
             ('watching', 335),
             ('already', 749),
             ('bleeding', 17),
             ('edge', 133),
             ('clever', 16),
             ('cross', 96),
             ('between', 185),
             ('overwatch', 891),
             ('domination', 9),
             ('mode', 398),
             ('as', 3099),
             ('crossroads', 1),
             ('future', 157),
             ('2016', 95),
             ('fantasy', 111),
             ('non', 78),
             ('bioshock', 25),
             ('switch', 230),
             ('count', 53),
             ('desert', 13),
             ('montana', 1),
             ('after', 1521),
             ('platinum', 48),
             ('loot', 112),
             ('booty', 15),
             ('lot', 567),
             ('has', 2715),
             ('named', 39),
             ('reason', 345),
             ('laptop', 100),
             ('run', 355),
             ('war', 655),
             ('thunder', 23),
             ('warframe', 5),
             ('high', 310),
             ('settings', 75),
             ('moment', 179),
             ('launch', 321),
             ('csgo', 765),
             ('computer', 151),
             ('crashes', 130),
             ('whole', 451),
             ('breaks', 32),
             ('down', 933),
             ('firefox', 36),
             ('plus', 162),
             ('no', 2810),
             ('easily', 72),
             ('currently', 307),
             ('dare', 23),
             ('mind', 192),
             ('software', 127),
             ('mount', 49),
             ('act', 72),
             ('king', 100),
             ('speeds', 54),
             ('jumping', 51),
             ('more', 2563),
             ('dlcs', 13),
             ('vibing', 3),
             ('playlists', 15),
             ('vibe', 28),
             ('dropping', 73),
             ('quality', 145),
             ('720p', 4),
             ('makes', 521),
             ('difference', 57),
             ('well', 972),
             ('runs', 105),
             ('dumb', 131),
             ('internet', 433),
             ('lmao', 222),
             ('heyitscece', 3),
             ('streaming', 271),
             ('vibrating', 1),
             ('lowering', 5),
             ('jon', 20),
             ('downloading', 49),
             ('tumb', 2),
             ('enter', 101),
             ('gunner', 12),
             ('seat', 20),
             ('fear', 68),
             ('step', 204),
             ('trench', 1),
             ('then', 1160),
             ('wav1bacr5j', 4),
             ('wikipedia', 216),
             ('org', 382),
             ('v', 1007),
             ('omg', 219),
             ('ever', 1230),
             ('thwarted', 4),
             ('bank', 78),
             ('foiled', 1),
             ('threatened', 14),
             ('who', 1544),
             ('late', 182),
             ('trip', 43),
             ('seems', 315),
             ('broken', 376),
             ('with', 7195),
             ('m10', 6),
             ('rates', 18),
             ('constantly', 83),
             ('less', 236),
             ('than', 1331),
             ('lower', 87),
             ('levels', 43),
             ('possible', 138),
             ('2500', 9),
             ('swear', 96),
             ('greens', 5),
             ('blues', 23),
             ('boss', 75),
             ('falling', 53),
             ('when', 2618),
             ('rate', 83),
             ('production', 57),
             ('kinda', 225),
             ('pushing', 37),
             ('normal', 85),
             ('people', 2110),
             ('moving', 75),
             ('recovery', 41),
             ('fast', 173),
             ('next', 854),
             ('gold', 251),
             ('amounts', 12),
             ('worked', 158),
             ('polycule', 4),
             ('tonight', 384),
             ('magical', 23),
             ('evening', 61),
             ('end', 413),
             ('sigh', 27),
             ('allowed', 45),
             ('polyphony', 1),
             ('polyslice', 1),
             ('better', 758),
             ('part', 410),
             ('same', 745),
             ('jackson', 50),
             ('happy', 909),
             ('profit', 40),
             ('wise', 27),
             ('expected', 68),
             ('due', 326),
             ('budget', 32),
             ('realize', 74),
             ('because', 1753),
             ('busted', 29),
             ('again', 1352),
             ('only', 1567),
             ('marketing', 87),
             ('business', 396),
             ('prior', 3),
             ('problem', 507),
             ('far', 424),
             ('always', 807),
             ('fav', 49),
             ('certainly', 97),
             ('guardian', 24),
             ('around', 444),
             ('weekend', 260),
             ('managed', 75),
             ('done', 621),
             ('enjoying', 136),
             ('loved', 216),
             ('slutty', 5),
             ('mechanic', 29),
             ('slutsky', 1),
             ('old', 579),
             ('night', 532),
             ('heeps', 4),
             ("we're", 190),
             ('closer', 31),
             ('towards', 102),
             ('raided', 16),

In [117]:
sequences = tokenizer.texts_to_sequences(train['Tweets'])

In [118]:
sequences

[[3, 114, 400, 4, 2, 6290, 5, 3, 56, 455, 15, 28],
 [314, 171, 14, 121, 5, 3, 56, 455, 15, 28],
 [314, 400, 14, 121, 5, 3, 56, 1737, 15, 28],
 [314, 171, 14, 121, 32, 5, 3, 56, 1737, 15, 22, 28],
 [314, 171, 191, 121, 5, 3, 47, 1737, 15, 28],
 [20,
  3,
  798,
  6,
  361,
  347,
  324,
  240,
  10,
  133,
  49,
  15,
  130,
  125,
  3,
  114,
  6,
  496,
  121,
  629,
  5,
  3924,
  8,
  46,
  7,
  13,
  328,
  749,
  20,
  3,
  739,
  4,
  123,
  491,
  6,
  5328,
  10,
  13,
  282,
  145,
  8,
  2,
  762,
  2053,
  5577,
  2,
  8859,
  3,
  213,
  425,
  38,
  39,
  17,
  15636],
 [20,
  3,
  798,
  6,
  1012,
  7,
  347,
  308,
  240,
  10,
  133,
  49,
  15,
  130,
  125,
  16,
  61,
  6,
  496,
  121,
  629,
  5,
  3924,
  8,
  46,
  7,
  13,
  328,
  749,
  3,
  739,
  4,
  123,
  6,
  5328,
  10,
  13,
  282,
  1189,
  2,
  762,
  1467,
  1819,
  4,
  2,
  8859,
  3,
  213,
  23,
  133,
  38,
  39,
  17,
  15636],
 [20,
  3,
  798,
  6,
  361,
  347,
  308,
  240,
  10,
  133,
  49,
  15,
  130,
  125,
  61,
  6,
  496,
  121,
  629,
  5,
  3924,
  8,
  46,
  7,
  13,
  328,
  749],
 [20,
  3,
  798,
  6,
  361,
  347,
  324,
  240,
  10,
  133,
  49,
  15,
  130,
  125,
  3,
  114,
  6,
  496,
  96,
  629,
  5,
  3924,
  8,
  46,
  7,
  13,
  328,
  749,
  20,
  3,
  739,
  4,
  123,
  491,
  6,
  5328,
  10,
  13,
  282,
  145,
  8,
  2,
  762,
  2053,
  5577,
  2,
  8859,
  3,
  213,
  425,
  38,
  39,
  17,
  15636],
 [1889,
  20,
  3,
  798,
  6,
  361,
  347,
  324,
  240,
  10,
  133,
  49,
  15,
  130,
  125,
  3,
  114,
  6,
  496,
  96,
  629,
  5,
  3924,
  8,
  46,
  7,
  13,
  328,
  749,
  20,
  3,
  739,
  4,
  123,
  491,
  6,
  5328,
  10,
  13,
  282,
  145,
  8,
  2,
  762,
  2053,
  5577,
  2,
  8859,
  3,
  213,
  425,
  38,
  39,
  17,
  15636],
 [29],
 [1698, 358, 1660, 15637, 2939, 918, 1699, 7266, 121, 66, 90, 528, 11, 8860],
 [1698, 358, 1660, 15637, 2939, 918, 1699, 7266, 121, 66, 90, 528, 11, 8860],
 [1698, 358, 1660, 15637, 2939, 918, 1699, 7266, 121, 66, 90, 8237, 11, 8860],
 [1698,
  358,
  1660,
  5860,
  2939,
  25,
  918,
  1699,
  7266,
  121,
  88,
  90,
  528,
  11,
  8860],
 [215,
  1698,
  358,
  552,
  1660,
  1660,
  15637,
  2939,
  2,
  918,
  215,
  1699,
  3,
  7266,
  121,
  66,
  3479,
  90,
  528,
  34,
  11,
  426,
  8860],
 [3, 358, 31, 22, 2939, 4050, 1274, 1699, 2349, 121, 66, 90, 528, 11, 8860],
 [16,
  29,
  2,
  122,
  121,
  1626,
  9,
  6,
  293,
  63,
  274,
  3,
  201,
  103,
  6,
  57,
  2254,
  1923,
  525,
  3,
  87,
  71,
  57,
  51,
  723],
 [12,
  29,
  2,
  122,
  121,
  1626,
  9,
  6,
  293,
  63,
  274,
  3,
  201,
  103,
  6,
  57,
  2254,
  1924,
  525,
  3,
  87,
  71,
  57,
  51,
  723],
 [16,
  29,
  2,
  122,
  121,
  1626,
  9,
  6,
  293,
  63,
  274,
  3,
  201,
  876,
  6,
  57,
  2254,
  1923,
  525,
  3,
  87,
  71,
  1066,
  51,
  723],
 [16,
  3,
  29,
  2,
  122,
  318,
  121,
  1626,
  9,
  6,
  249,
  293,
  152,
  63,
  274,
  3,
  201,
  103,
  6,
  57,
  2254,
  1923,
  525,
  5,
  3,
  87,
  71,
  57,
  51,
  723],
 [16,
  29,
  2,
  122,
  121,
  1626,
  9,
  6,
  732,
  984,
  274,
  3,
  201,
  103,
  6,
  57,
  144,
  1923,
  525,
  3,
  200,
  71,
  57,
  51,
  723],
 [2, 799, 15638, 9, 13, 289, 554, 33, 6, 164, 507, 98, 121, 66],
 [2, 799, 1838, 7, 13, 289, 554, 6, 164, 507],
 [2, 799, 15638, 9, 13, 289, 400, 33, 6, 164, 507, 98, 121, 66],
 [10,
  2,
  799,
  4636,
  15638,
  9,
  13,
  289,
  554,
  1839,
  33,
  6,
  164,
  63,
  507,
  98,
  121,
  66],
 [2, 799, 15638, 9, 13, 289, 554, 102, 181, 164, 507, 98, 121, 181],
 [42,
  519,
  121,
  66,
  224,
  6741,
  157,
  15,
  10,
  1839,
  33,
  218,
  11,
  29,
  133,
  3,
  56,
  341,
  4,
  273,
  508,
  25,
  49,
  26,
  3,
  504,
  20,
  71,
  2392,
  1979,
  223,
  15639,
  42,
  2570,
  89,
  157,
  15,
  20,
  110,
  10,
  2,
  3214,
  8861,
  8862,
  15640,
  5,
  18813],
 [42,
  224,
  224,
  377,
  121,
  66,
  557,
  157,
  15,
  28,
  10,
  1839,
  33,
  11,
  29,
  133,
  497,
  341,
  4,
  273,
  508,
  25,
  49,
  26,
  399,
  71,
  2392,
  1979,
  2014,
  89,
  177,
  10,
  2,
  3214,
  8861,
  8862,
  15640,
  5,
  18813],
 [157,
  15,
  10,
  1839,
  60,
  218,
  11,
  29,
  133,
  497,
  341,
  4,
  37,
  6,
  7738,
  508,
  25,
  49,
  11,
  1483,
  10,
  22,
  71,
  2392,
  1979,
  129,
  77,
  21,
  9,
  18814,
  2014,
  89,
  157,
  15,
  20,
  110,
  10,
  2,
  8861,
  8862,
  22914,
  5,
  22915,
  3214],
 [42,
  519,
  121,
  66,
  229,
  6741,
  157,
  15,
  10,
  1839,
  33,
  188,
  11,
  29,
  133,
  3,
  56,
  341,
  4,
  273,
  5,
  91,
  49,
  26,
  3,
  504,
  20,
  71,
  2392,
  1979,
  223,
  15639,
  42,
  2570,
  97,
  157,
  15,
  20,
  110,
  10,
  2,
  3214,
  8861,
  8862,
  15640,
  5,
  362],
 [42,
  519,
  121,
  66,
  5,
  224,
  6741,
  157,
  15,
  218,
  10,
  1839,
  33,
  218,
  11,
  29,
  133,
  3,
  56,
  341,
  4,
  123,
  273,
  508,
  25,
  49,
  26,
  3,
  504,
  123,
  20,
  71,
  2392,
  1979,
  223,
  15639,
  165,
  42,
  156,
  2570,
  89,
  157,
  15,
  310,
  20,
  110,
  10,
  2,
  3214,
  8861,
  8862,
  67,
  15640,
  5,
  136,
  18813],
 [42,
  519,
  121,
  66,
  224,
  6741,
  311,
  15,
  10,
  1839,
  33,
  20,
  11,
  29,
  133,
  3,
  56,
  341,
  16,
  273,
  508,
  5,
  49,
  26,
  3,
  504,
  307,
  71,
  2392,
  1979,
  34,
  15639,
  42,
  2570,
  89,
  157,
  15,
  20,
  110,
  68,
  234,
  3214,
  8861,
  8862,
  200,
  5,
  116],
 [205,
  3142,
  57,
  526,
  4,
  119,
  12,
  18815,
  1339,
  9,
  2,
  50,
  121,
  66,
  888,
  385,
  21,
  997,
  4,
  3684,
  4845,
  14,
  1797,
  165,
  4,
  37,
  88,
  1058,
  822,
  223,
  1236,
  537,
  3,
  37,
  260,
  165,
  1339,
  57,
  530,
  3074],
 [205,
  3142,
  57,
  526,
  4,
  119,
  135,
  1484,
  1339,
  9,
  2,
  50,
  121,
  66,
  888,
  10,
  3684,
  4845,
  14,
  1797,
  165,
  4,
  37,
  6,
  1058,
  822,
  223,
  3,
  37,
  260,
  165,
  1339,
  5578],
 [205,
  3142,
  57,
  526,
  4,
  119,
  12,
  22916,
  1339,
  9,
  2,
  50,
  121,
  66,
  888,
  385,
  21,
  997,
  4,
  3684,
  4845,
  14,
  1797,
  165,
  4,
  37,
  88,
  1058,
  822,
  223,
  5578,
  3,
  37,
  260,
  165,
  1339,
  57,
  530,
  3074],
 [205,
  3004,
  57,
  526,
  4,
  119,
  12,
  18815,
  1339,
  5,
  2,
  50,
  121,
  66,
  11,
  385,
  21,
  997,
  4,
  3684,
  4845,
  14,
  1797,
  165,
  4,
  37,
  88,
  1058,
  822,
  223,
  1236,
  537,
  3,
  37,
  260,
  165,
  1339,
  57,
  530],
 [205,
  3142,
  57,
  526,
  4,
  119,
  12,
  18815,
  1339,
  9,
  2,
  558,
  50,
  121,
  66,
  263,
  888,
  3,
  385,
  426,
  21,
  997,
  264,
  4,
  21,
  3684,
  4845,
  14,
  1797,
  165,
  4,
  426,
  37,
  88,
  1058,
  2667,
  822,
  223,
  1236,
  537,
  3,
  37,
  260,
  165,
  1339,
  11,
  57,
  530,
  4,
  3074],
 [65,
  3142,
  57,
  63,
  4,
  119,
  12,
  165,
  1339,
  9,
  2,
  50,
  121,
  66,
  888,
  67,
  21,
  997,
  4,
  1307,
  4845,
  14,
  1797,
  165,
  4,
  37,
  6,
  1058,
  822,
  223,
  218,
  537,
  3,
  37,
  260,
  165,
  1339,
  57,
  526,
  3074],
 [287, 33, 12, 444, 2393],
 [287, 33, 12, 444, 2393],
 [180, 12, 444, 20702],
 [287, 33, 127, 444, 2393],
 [287, 33, 12, 228, 444, 2393],
 [287, 65, 12, 444, 2393],
 [7739,
  3925,
  10,
  20703,
  6,
  334,
  272,
  7,
  121,
  3,
  87,
  623,
  9,
  656,
  10,
  174,
  508,
  20,
  3,
  120,
  123,
  60,
  63,
  522,
  13,
  2285,
  167,
  131,
  18816],
 [6,
  272,
  7,
  5861,
  3,
  29,
  623,
  4,
  174,
  508,
  531,
  20,
  3,
  120,
  2133,
  60,
  522,
  13,
  64,
  167,
  131,
  18816],
 [2894,
  7,
  22917,
  6,
  272,
  7,
  6,
  11941,
  3,
  29,
  623,
  4,
  174,
  656,
  508,
  20,
  3,
  120,
  2133,
  60],
 [10,
  7739,
  3925,
  10,
  20703,
  6,
  334,
  272,
  7,
  121,
  3,
  87,
  623,
  9,
  656,
  10,
  174,
  508,
  20,
  3,
  120,
  123,
  60,
  63,
  522,
  13,
  2285,
  167,
  131,
  18816],
 [28],
 [69,
  288,
  31,
  151,
  205,
  9,
  121,
  23,
  15641,
  102,
  1218,
  1351,
  15,
  932,
  7,
  11942,
  15,
  366,
  2435],
 [69, 31, 151, 205, 9, 2609, 3926, 23, 15, 26, 932, 7, 11942, 15, 366, 2435],
 [69,
  31,
  218,
  537,
  9,
  2,
  2609,
  3926,
  23,
  35,
  1218,
  3392,
  175,
  23,
  15,
  26,
  932,
  16,
  15,
  27,
  366,
  3927],
 [69,
  288,
  31,
  65,
  205,
  9,
  121,
  23,
  15641,
  102,
  1218,
  67,
  15,
  932,
  7,
  11942,
  15,
  366,
  2435],
 [69,
  7267,
  288,
  31,
  151,
  205,
  9,
  121,
  23,
  553,
  15641,
  16,
  102,
  1218,
  2481,
  79,
  41,
  15,
  932,
  423,
  7,
  6291,
  11942,
  15,
  366,
  2435],
 [69,
  288,
  4846,
  151,
  205,
  9,
  15642,
  23,
  15641,
  102,
  1218,
  1351,
  15,
  932,
  7,
  11942,
  2,
  2436,
  2435],
 [],
 [],
 [2529],
 [62],
 [112,
  4,
  976,
  60,
  121,
  32,
  143,
  172,
  87,
  71,
  50,
  3582,
  625,
  60,
  5,
  114,
  290,
  485,
  4,
  6,
  51,
  273,
  641,
  9,
  53,
  114,
  581],
 [3,
  56,
  976,
  121,
  32,
  143,
  3,
  23,
  71,
  50,
  3582,
  625,
  60,
  5,
  114,
  290,
  485,
  4,
  6,
  51,
  273,
  329,
  9,
  53,
  54,
  581],
 [61,
  112,
  4,
  976,
  121,
  32,
  143,
  3,
  23,
  71,
  50,
  3582,
  1588,
  5,
  61,
  290,
  485,
  4,
  6,
  51,
  273],
 [112,
  4,
  976,
  60,
  121,
  32,
  143,
  172,
  87,
  71,
  50,
  1412,
  625,
  60,
  5,
  114,
  222,
  485,
  4,
  6,
  51,
  273,
  641,
  9,
  53,
  256,
  581],
 [112,
  4,
  976,
  976,
  7268,
  60,
  121,
  32,
  143,
  172,
  24,
  87,
  291,
  71,
  50,
  3582,
  625,
  28,
  60,
  5,
  114,
  290,
  485,
  11,
  4,
  6,
  51,
  273,
  641,
  9,
  53,
  114,
  581],
 [112,
  4,
  976,
  60,
  4184,
  32,
  143,
  172,
  87,
  71,
  271,
  520,
  625,
  60,
  5,
  8,
  290,
  485,
  4,
  6,
  51,
  273,
  641,
  9,
  53,
  114,
  581],
 [2033, 350, 43, 71, 121, 6292, 9, 6, 272, 5329, 21, 133],
 [2033, 8, 350, 86, 6, 272, 7, 5861, 6292, 16, 56, 21, 133],
 [2033, 56, 350, 43, 71, 2609, 6292, 9, 6, 272, 74, 112, 4, 21, 133],
 [2033, 350, 43, 215, 121, 6292, 9, 6, 272, 5329, 21, 133],
 [10, 2033, 350, 43, 71, 121, 6292, 9, 6, 272, 22918, 1398, 21, 6, 133],
 [2033, 350, 87, 71, 159, 6292, 9, 6, 272, 5329, 123, 133],
 [46,
  7,
  127,
  393,
  11943,
  8,
  215,
  430,
  121,
  20704,
  2133,
  305,
  145,
  967,
  281,
  8863,
  219,
  2393,
  4314,
  9,
  1137,
  10,
  6,
  379,
  4,
  21,
  9,
  6,
  400,
  2393,
  4314,
  1426,
  33],
 [46,
  7,
  127,
  393,
  11943,
  8,
  215,
  430,
  121,
  66,
  2133,
  305,
  145,
  967,
  281,
  8863,
  219,
  2393,
  4314,
  9,
  1137,
  10,
  6,
  379,
  4,
  21,
  9,
  54,
  1840,
  46,
  2393,
  4314,
  1426,
  33],
 [46,
  7,
  127,
  393,
  22919,
  215,
  430,
  121,
  66,
  2133,
  305,
  145,
  967,
  281,
  8863,
  219,
  273,
  4314,
  9,
  1137,
  10,
  6,
  1137,
  10,
  6,
  379,
  4,
  21,
  9,
  6,
  400,
  273,
  4314,
  1426,
  33],
 [46,
  7,
  127,
  393,
  11943,
  8,
  215,
  121,
  20704,
  2133,
  305,
  145,
  967,
  281,
  8863,
  468,
  219,
  71,
  4314,
  9,
  1137,
  758,
  6,
  379,
  4,
  21,
  9,
  6,
  400,
  141,
  1426,
  33],
 [46,
  7,
  127,
  846,
  393,
  11943,
  8,
  215,
  225,
  430,
  30,
  121,
  66,
  5,
  65,
  2133,
  305,
  145,
  2,
  967,
  281,
  4,
  8863,
  4,
  219,
  2393,
  4314,
  9,
  1137,
  10,
  6,
  379,
  4,
  1520,
  21,
  9,
  6,
  162,
  400,
  2393,
  4314,
  88,
  1426,
  33],
 [46,
  7,
  118,
  393,
  2839,
  8,
  215,
  430,
  11943,
  66,
  2133,
  305,
  34,
  967,
  281,
  8863,
  10,
  2393,
  4314,
  9,
  7740,
  67,
  6,
  379,
  4,
  21,
  33,
  6,
  400,
  28,
  66,
  20705],
 [98, 15643],
 [11944, 20706],
 [98, 15643],
 [98, 15643, 65],
 [6, 98, 15643],
 [98, 15],
 [3,
  258,
  16,
  12,
  667,
  1797,
  6293,
  556,
  14,
  1797,
  1150,
  181,
  942,
  12,
  8,
  2,
  142,
  133,
  492,
  103,
  9,
  2,
  18,
  226,
  45,
  1138,
  104,
  1322,
  3928,
  121,
  99,
  266,
  22,
  2,
  1031,
  4,
  43,
  1797,
  165,
  25,
  708,
  2,
  3928,
  175,
  825],
 [3,
  258,
  16,
  12,
  1085,
  2571,
  6293,
  556,
  14,
  2571,
  459,
  181,
  942,
  351,
  2,
  142,
  133,
  172,
  103,
  9,
  2,
  18,
  226,
  45,
  1138,
  523,
  3928,
  121,
  99,
  266,
  22,
  2,
  1031,
  4,
  43,
  2571,
  165,
  25,
  708,
  175,
  2,
  3928],
 [3,
  258,
  16,
  12,
  667,
  1797,
  6293,
  556,
  14,
  1797,
  459,
  181,
  942,
  12,
  8,
  2,
  142,
  133,
  172,
  103,
  9,
  2,
  18,
  226,
  45,
  1138,
  104,
  1322,
  3928,
  121,
  99,
  266,
  22,
  2,
  1031,
  4,
  43,
  1797,
  165,
  25,
  708,
  2,
  3928,
  175,
  825],
 [3,
  258,
  548,
  12,
  667,
  134,
  473,
  556,
  14,
  1797,
  1150,
  181,
  942,
  12,
  8,
  2,
  142,
  133,
  492,
  103,
  9,
  2,
  18,
  226,
  45,
  1138,
  104,
  1322,
  3928,
  121,
  99,
  266,
  22,
  71,
  2437,
  4,
  43,
  1797,
  165,
  25,
  708,
  2,
  3928,
  175,
  825],
 [3,
  258,
  768,
  16,
  12,
  667,
  1797,
  6293,
  556,
  14,
  1179,
  1797,
  344,
  79,
  41,
  181,
  942,
  12,
  8,
  2,
  412,
  142,
  793,
  133,
  525,
  3,
  79,
  760,
  103,
  9,
  2,
  18,
  356,
  226,
  45,
  1138,
  104,
  1322,
  3928,
  121,
  99,
  48,
  266,
  22,
  2,
  1031,
  1031,
  4,
  6,
  43,
  1797,
  165,
  25,
  708,
  2,
  3928,
  175,
  825],
 [3,
  258,
  16,
  12,
  667,
  1322,
  6293,
  556,
  14,
  18,
  165,
  181,
  942,
  16,
  8,
  2,
  83,
  133,
  492,
  604,
  9,
  2,
  664,
  335,
  45,
  1138,
  104,
  1322,
  3928,
  121,
  99,
  1261,
  22,
  2,
  1031,
  4,
  43,
  1797,
  165,
  25,
  708,
  2,
  3928,
  10,
  825],
 [11945,
  356,
  1167,
  299,
  303,
  91,
  642,
  2,
  121,
  1798,
  8864,
  1721,
  335,
  11,
  1533,
  360,
  206,
  4315,
  11946,
  18,
  3,
  57,
  365,
  152,
  10,
  12,
  968,
  2721,
  4,
  571],
 [11945,
  1167,
  303,
  642,
  2,
  11941,
  8864,
  1721,
  335,
  11,
  1533,
  206,
  4315,
  11946,
  18,
  3,
  57,
  120,
  152,
  10,
  12,
  2438,
  2721,
  4,
  571],
 [22920,
  1167,
  299,
  303,
  91,
  642,
  2,
  8864,
  5862,
  335,
  11,
  1122,
  191,
  206,
  4315,
  18,
  3,
  57,
  120,
  152,
  10,
  12,
  794,
  2721,
  4,
  571],
 [11945,
  356,
  1167,
  299,
  303,
  145,
  642,
  2,
  121,
  1798,
  8864,
  1721,
  335,
  11,
  1533,
  360,
  54,
  4315,
  11946,
  18,
  3,
  57,
  365,
  152,
  10,
  12,
  968,
  4455,
  4,
  571],
 [1644,
  11945,
  356,
  1167,
  299,
  303,
  91,
  642,
  2,
  121,
  4847,
  1798,
  8864,
  1721,
  3781,
  335,
  8238,
  11,
  1533,
  360,
  206,
  4315,
  11946,
  323,
  18,
  3,
  57,
  47,
  79,
  41,
  152,
  10,
  12,
  968,
  2721,
  641,
  4,
  571],
 [11945,
  356,
  29,
  299,
  303,
  91,
  642,
  2,
  312,
  1798,
  8864,
  1721,
  335,
  42,
  1533,
  360,
  206,
  602,
  11946,
  18,
  3,
  582,
  365,
  152,
  14,
  12,
  968,
  2721,
  4,
  571],
 [121, 68, 48, 3, 3215, 6, 3216, 35, 2840, 929, 1323, 245, 1559, 116, 4185],
 [121, 68, 47, 3, 1521, 6, 3216, 35, 2840, 373, 376, 245, 1041, 116, 4185],
 [121, 68, 4, 1521, 6, 3216, 35, 2840, 373, 376, 245, 1041, 4185],
 [121, 68, 200, 3, 3215, 6, 3216, 35, 2840, 929, 1323, 245, 4848, 116, 4185],
 [121,
  68,
  48,
  3782,
  3,
  3215,
  6,
  3216,
  35,
  2840,
  22921,
  41,
  91,
  1323,
  245,
  619,
  1559,
  116,
  4185],
 [36, 68, 48, 3, 3215, 184, 3216, 35, 2840, 929, 3393, 245, 1559, 116, 4185],
 [28, 2, 121, 27, 1262, 415],
 [28, 2, 121, 27, 202, 4316],
 [28, 2, 121, 27, 100, 2572],
 [28, 2, 121, 73, 1262, 415],
 [1951, 28, 2, 121, 27, 1262, 415],
 [28, 2, 121, 27, 1262, 366],
 [224,
  179,
  300,
  121,
  66,
  2,
  1032,
  18,
  43,
  8,
  93,
  356,
  28,
  2054,
  306,
  133,
  5,
  3,
  156,
  560,
  952,
  31,
  3,
  1151,
  4,
  1679,
  16,
  357,
  14,
  2,
  251,
  1093,
  28,
  3,
  56,
  219,
  8,
  16,
  61,
  138,
  110,
  20,
  290,
  485,
  4,
  2,
  11947,
  5081,
  4456],
 [224,
  179,
  70,
  121,
  66,
  2,
  1032,
  18,
  8,
  93,
  356,
  28,
  1437,
  306,
  671,
  5,
  3,
  156,
  952,
  31,
  3,
  103,
  4,
  1679,
  14,
  2,
  251,
  1093,
  28,
  3,
  56,
  219,
  8,
  16,
  3,
  114,
  138,
  110,
  290,
  485,
  4,
  2,
  11947,
  8239,
  4456],
 [12,
  357,
  14,
  2,
  251,
  1093,
  28,
  3,
  56,
  219,
  8,
  16,
  61,
  290,
  485,
  4,
  54,
  20707,
  8240],
 [224,
  179,
  300,
  121,
  66,
  2,
  390,
  18,
  43,
  8,
  93,
  356,
  28,
  2054,
  306,
  133,
  5,
  3,
  156,
  560,
  952,
  31,
  3,
  1151,
  4,
  1679,
  2,
  357,
  14,
  4,
  206,
  1093,
  28,
  3,
  56,
  219,
  8,
  16,
  61,
  138,
  110,
  20,
  290,
  485,
  4,
  118,
  11947,
  5081,
  4456],
 [224,
  179,
  300,
  121,
  66,
  2,
  1032,
  18,
  3,
  43,
  8,
  93,
  356,
  28,
  2054,
  306,
  133,
  5,
  360,
  3,
  156,
  560,
  952,
  110,
  31,
  297,
  3,
  582,
  1151,
  4,
  1679,
  16,
  299,
  357,
  14,
  2,
  251,
  861,
  1093,
  28,
  3,
  56,
  219,
  8,
  16,
  61,
  138,
  202,
  110,
  20,
  485,
  290,
  485,
  4,
  2,
  11947,
  3217,
  5081,
  4456],
 [224,
  179,
  300,
  121,
  108,
  2,
  1032,
  18,
  43,
  8,
  93,
  356,
  28,
  2054,
  246,
  133,
  5,
  3,
  156,
  560,
  952,
  371,
  3,
  1151,
  4,
  1679,
  16,
  357,
  8,
  2,
  251,
  1093,
  25,
  3,
  56,
  219,
  36,
  302,
  22922,
  138,
  110,
  20,
  290,
  485,
  4,
  2,
  4051,
  5081,
  4456],
 [254, 1363, 46, 7, 2, 1627, 348, 11948],
 [1363, 46, 7, 2, 1627, 3783, 11948],
 [254, 1363, 46, 7, 2, 404, 2940, 7, 3783],
 [254, 4, 46, 7, 2, 1627, 348, 11948],
 [1042, 254, 1363, 46, 7, 2, 1627, 348, 11948],
 [254, 1363, 46, 7, 2, 1627, 1738, 11948],
 [62, 6, 832],
 [62, 6, 6742],
 [62, 523, 832],
 [62, 6, 832],
 [62, 6, 3394],
 [566,
  3,
  114,
  926,
  12,
  141,
  86,
  4457,
  124,
  15644,
  9,
  381,
  438,
  22,
  1438,
  138,
  121,
  31,
  5,
  2,
  1925,
  8,
  7269],
 [566,
  61,
  926,
  12,
  141,
  86,
  4457,
  124,
  15644,
  9,
  240,
  1077,
  22,
  6,
  1438,
  138,
  121,
  31,
  5,
  2,
  1925,
  8,
  7269],
 [566,
  3,
  114,
  926,
  12,
  141,
  86,
  4457,
  124,
  22923,
  9,
  381,
  438,
  22,
  145,
  138,
  121,
  31,
  5,
  2,
  1925,
  8,
  7269],
 [566,
  3,
  114,
  926,
  12,
  141,
  636,
  257,
  124,
  15644,
  9,
  381,
  438,
  22,
  1438,
  138,
  121,
  31,
  5,
  2,
  1925,
  8,
  271],
 [566,
  1799,
  3,
  114,
  926,
  12,
  141,
  24,
  86,
  4457,
  124,
  15644,
  5,
  9,
  1102,
  381,
  438,
  118,
  22,
  1438,
  3,
  138,
  121,
  31,
  5,
  2,
  1925,
  8,
  7269],
 [566,
  3,
  114,
  926,
  12,
  141,
  86,
  4457,
  5,
  2161,
  9,
  381,
  438,
  22,
  1438,
  138,
  51,
  2573,
  5,
  2,
  1925,
  8,
  7269],
 [24, 2482, 28, 7, 13, 251, 82, 4, 123, 1439, 10, 121, 66],
 [24, 4637, 28, 13, 251, 82, 4, 123, 1094, 10, 121, 66],
 [24, 1127, 28, 13, 251, 82, 4, 123, 1094, 10, 121, 66],
 [24, 2482, 28, 7, 13, 251, 82, 56, 123, 1439, 10, 121, 66],
 [24, 2482, 28, 251, 7, 13, 13, 251, 82, 4, 123, 1439, 10, 469, 121, 66],
 [24, 2482, 28, 7, 28, 251, 82, 9, 123, 1439, 10, 121, 66],
 [242,
  926,
  4638,
  1003,
  62,
  6,
  4849,
  18,
  1308,
  773,
  203,
  121,
  5,
  7270,
  18,
  405,
  303,
  40],
 [3,
  64,
  4638,
  1003,
  62,
  6,
  4849,
  18,
  22924,
  7,
  203,
  121,
  5,
  7270,
  18,
  405,
  303,
  40],
 [1308, 773, 203, 121, 5, 7270, 18, 405, 303, 40],
 [242,
  926,
  4638,
  1003,
  62,
  6,
  133,
  18,
  1308,
  773,
  203,
  121,
  5,
  90,
  18,
  405,
  303,
  40],
 [242,
  141,
  926,
  2,
  4638,
  1003,
  62,
  8,
  6,
  4849,
  18,
  1308,
  773,
  203,
  121,
  5,
  886,
  7270,
  18,
  405,
  1324,
  303,
  33,
  40],
 [242,
  179,
  4638,
  1003,
  62,
  6,
  4849,
  18,
  1308,
  773,
  1162,
  121,
  1534,
  7270,
  18,
  405,
  86,
  40],
 [3583, 5, 121, 400, 4, 2, 624, 832, 2101, 22, 2, 98, 9],
 [3583, 5, 121, 400, 4, 2, 624, 832, 2101, 22, 2, 98, 9],
 [3583, 5, 121, 400, 4, 2, 5579, 832, 2101, 22, 2, 98, 9],
 [3583, 22925, 5, 251, 121, 27, 400, 4, 2, 624, 832, 2101, 22, 2, 98, 9],
 [3583, 5, 121, 400, 113, 35, 624, 832, 2101, 22, 2, 98, 9],
 [2255, 8, 2, 83, 1152, 121],
 [2255, 8, 2, 83, 5082, 121],
 [2255, 8, 2, 83, 304, 121],

In [119]:
len((sequences[0]))

12

In [120]:
len(sequences[1])

10

In [121]:
len(sequences[2])

10

In [122]:
from keras.utils import pad_sequences

### Padding the sequences :
- When we convert text into sequence of numbers, we get sequences of different lengths.
- But for training a model, we need all the sequences to be of the same length.
- So we use padding to make all the sequences of the same length.
- pad as pre or post. 
- If we pad as pre, then we add zeros at the beginning of the sequence.
- If we pad as post, then we add zeros at the end of the sequence.

In [123]:
sequences = pad_sequences(sequences, padding='pre')

In [124]:
sequences

array([[   0,    0,    0, ...,  455,   15,   28],
       [   0,    0,    0, ...,  455,   15,   28],
       [   0,    0,    0, ..., 1737,   15,   28],
       ...,
       [   0,    0,    0, ...,  154, 1028, 2541],
       [   0,    0,    0, ...,   79,   41, 2541],
       [   0,    0,    0, ...,    3, 1028, 2541]], dtype=int32)

### Text --> [Integer Sequence] --> [Padded Integer Sequence] --> Model

In [125]:
from keras.layers import SimpleRNN, Embedding, Dense,Input
from keras.models import Sequential

In [126]:
X = sequences

In [127]:
y = train['Sentiment'].values

In [128]:
y

array([2, 2, 2, ..., 2, 2, 2])

In [129]:
from sklearn.model_selection import train_test_split

In [130]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [131]:
x_train.shape

(47294, 166)

### Embedding Layer :
- It is used to convert the integer sequences into dense vectors of fixed size.
- After including the embedding layer, we capture the semantic meaning of the words in the text.

In [132]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(166,1),return_sequences=False))
model.add(Dense(3, activation='softmax')) 
## softmax is used for multi-class classification

/home/dharmender/anaconda3/lib/python3.10/site-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [133]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [134]:
## For multi-class classification, we use 'sparse_categorical_crossentropy' as the loss function and 'adam' as the optimizer. 
# We also track the accuracy metric during training.
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [135]:
model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test), batch_size=64)

Epoch 1/10
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.3571 - loss: 1.1141 - val_accuracy: 0.3737 - val_loss: 1.0920
Epoch 2/10
739/739 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3625 - loss: 1.0951 - val_accuracy: 0.3721 - val_loss: 1.0934
Epoch 3/10
739/739 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3630 - loss: 1.0953 - val_accuracy: 0.3736 - val_loss: 1.0931
Epoch 4/10
739/739 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3622 - loss: 1.0960 - val_accuracy: 0.3606 - val_loss: 1.0973
Epoch 5/10
739/739 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3556 - loss: 1.0979 - val_accuracy: 0.3731 - val_loss: 1.0976
Epoch 6/10
739/739 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3650 - loss: 1.0960 - val_accuracy: 0.3384 - val_loss: 1.0970
Epoch 7/10
739/739 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3590 - loss: 1.0965 - val_accuracy: 0.3408 - val_loss: 1.0960
Epoch 8/10
739/739 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3644 - loss: 1.0955 - val_accuracy: 0.3732 - val_loss: 1.0920
Epoch 9/10
739/739 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3606 - loss: 1.0953 - val_accuracy: 0.3738 - val_loss: 1.0919
Epoch 10/10
739/739 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.3606 - loss: 1.0948 - val_accuracy: 0.3720 - val_loss: 1.0920

### Vocab Size :
- It is the total number of unique words in the text.
- It is calculated as the length of the word index created by the tokenizer + 1 (to account for the OOV token).

In [136]:
vocab_size = len(tokenizer.word_index) + 1

In [137]:
vocab_size

29230

In [138]:
model_2 = Sequential()
model_2.add(Input(shape=(166,)))
model_2.add(Embedding(input_dim=vocab_size, output_dim=64)) ## input_length is not required as the input shape is already defined in the first layer
model_2.add(Dense(3, activation='softmax'))

In [139]:
model_2.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 166, 64)        │     1,870,720 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 166, 3)         │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,870,915 (7.14 MB)

 Trainable params: 1,870,915 (7.14 MB)

 Non-trainable params: 0 (0.00 B)

In [140]:
model_final = Sequential([
    Input(shape=(166,)),
    Embedding(input_dim=vocab_size, output_dim=64, mask_zero=True),
    SimpleRNN(32),
    Dense(3, activation='softmax')
])

In [141]:
model_final.compile(optimizer='adam', 
                    loss='sparse_categorical_crossentropy', 
                    metrics=['accuracy']
                    )

In [142]:
model_final.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 166, 64)        │     1,870,720 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ (None, 32)             │         3,104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,873,923 (7.15 MB)

 Trainable params: 1,873,923 (7.15 MB)

 Non-trainable params: 0 (0.00 B)

In [143]:
model_final.fit(x_train, y_train, epochs=100, validation_data=(x_test, y_test), batch_size=64)

Epoch 1/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.6307 - loss: 0.8092 - val_accuracy: 0.8617 - val_loss: 0.3583
Epoch 2/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9295 - loss: 0.1927 - val_accuracy: 0.8950 - val_loss: 0.2887
Epoch 3/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9614 - loss: 0.0960 - val_accuracy: 0.8976 - val_loss: 0.2943
Epoch 4/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9724 - loss: 0.0652 - val_accuracy: 0.8519 - val_loss: 0.4318
Epoch 5/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9673 - loss: 0.0803 - val_accuracy: 0.8743 - val_loss: 0.3833
Epoch 6/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9738 - loss: 0.0583 - val_accuracy: 0.8897 - val_loss: 0.3747
Epoch 7/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9781 - loss: 0.0482 - val_accuracy: 0.8879 - val_loss: 0.3860
Epoch 8/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9788 - loss: 0.0436 - val_accuracy: 0.8845 - val_loss: 0.4065
Epoch 9/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9780 - loss: 0.0459 - val_accuracy: 0.8808 - val_loss: 0.4200
Epoch 10/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9778 - loss: 0.0471 - val_accuracy: 0.8851 - val_loss: 0.4383
Epoch 11/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9773 - loss: 0.0455 - val_accuracy: 0.8802 - val_loss: 0.4580
Epoch 12/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9775 - loss: 0.0468 - val_accuracy: 0.8807 - val_loss: 0.4518
Epoch 13/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9773 - loss: 0.0449 - val_accuracy: 0.8843 - val_loss: 0.4424
Epoch 14/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9798 - loss: 0.0394 - val_accuracy: 0.8825 - val_loss: 0.4524
Epoch 15/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9809 - loss: 0.0386 - val_accuracy: 0.8832 - val_loss: 0.4541
Epoch 16/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9800 - loss: 0.0391 - val_accuracy: 0.8552 - val_loss: 0.5694
Epoch 17/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9785 - loss: 0.0441 - val_accuracy: 0.8779 - val_loss: 0.4733
Epoch 18/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9812 - loss: 0.0379 - val_accuracy: 0.8829 - val_loss: 0.4677
Epoch 19/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9803 - loss: 0.0392 - val_accuracy: 0.8841 - val_loss: 0.4674
Epoch 20/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9819 - loss: 0.0369 - val_accuracy: 0.8807 - val_loss: 0.4885
Epoch 21/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9805 - loss: 0.0382 - val_accuracy: 0.8698 - val_loss: 0.5072
Epoch 22/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9795 - loss: 0.0401 - val_accuracy: 0.8655 - val_loss: 0.5201
Epoch 23/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9799 - loss: 0.0398 - val_accuracy: 0.8809 - val_loss: 0.4724
Epoch 24/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9802 - loss: 0.0397 - val_accuracy: 0.8810 - val_loss: 0.4802
Epoch 25/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9814 - loss: 0.0365 - val_accuracy: 0.8867 - val_loss: 0.4656
Epoch 26/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9815 - loss: 0.0357 - val_accuracy: 0.8787 - val_loss: 0.4979
Epoch 27/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9814 - loss: 0.0368 - val_accuracy: 0.8777 - val_loss: 0.4947
Epoch 28/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9788 - loss: 0.0398 - val_accuracy: 0.8769 - val_loss: 0.4932
Epoch 29/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9807 - loss: 0.0360 - val_accuracy: 0.8729 - val_loss: 0.5257
Epoch 30/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9814 - loss: 0.0367 - val_accuracy: 0.8785 - val_loss: 0.5016
Epoch 31/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9812 - loss: 0.0366 - val_accuracy: 0.8772 - val_loss: 0.5028
Epoch 32/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9804 - loss: 0.0370 - val_accuracy: 0.8642 - val_loss: 0.5800
Epoch 33/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9759 - loss: 0.0510 - val_accuracy: 0.8741 - val_loss: 0.5361
Epoch 34/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9819 - loss: 0.0353 - val_accuracy: 0.8726 - val_loss: 0.5193
Epoch 35/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9798 - loss: 0.0367 - val_accuracy: 0.8809 - val_loss: 0.5137
Epoch 36/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9825 - loss: 0.0339 - val_accuracy: 0.8747 - val_loss: 0.5147
Epoch 37/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9827 - loss: 0.0331 - val_accuracy: 0.8787 - val_loss: 0.5107
Epoch 38/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9810 - loss: 0.0354 - val_accuracy: 0.8776 - val_loss: 0.5221
Epoch 39/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9810 - loss: 0.0359 - val_accuracy: 0.8684 - val_loss: 0.5393
Epoch 40/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9812 - loss: 0.0385 - val_accuracy: 0.8776 - val_loss: 0.4974
Epoch 41/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9823 - loss: 0.0339 - val_accuracy: 0.8793 - val_loss: 0.5054
Epoch 42/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9814 - loss: 0.0341 - val_accuracy: 0.8788 - val_loss: 0.5078
Epoch 43/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9824 - loss: 0.0334 - val_accuracy: 0.8827 - val_loss: 0.5060
Epoch 44/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9821 - loss: 0.0330 - val_accuracy: 0.8673 - val_loss: 0.5623
Epoch 45/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9816 - loss: 0.0334 - val_accuracy: 0.8794 - val_loss: 0.5207
Epoch 46/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9829 - loss: 0.0324 - val_accuracy: 0.8712 - val_loss: 0.5574
Epoch 47/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9796 - loss: 0.0390 - val_accuracy: 0.8713 - val_loss: 0.5460
Epoch 48/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9816 - loss: 0.0354 - val_accuracy: 0.8747 - val_loss: 0.5218
Epoch 49/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9819 - loss: 0.0342 - val_accuracy: 0.8698 - val_loss: 0.5440
Epoch 50/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9813 - loss: 0.0352 - val_accuracy: 0.8741 - val_loss: 0.5264
Epoch 51/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9824 - loss: 0.0332 - val_accuracy: 0.8754 - val_loss: 0.5291
Epoch 52/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9823 - loss: 0.0336 - val_accuracy: 0.8774 - val_loss: 0.5287
Epoch 53/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9807 - loss: 0.0339 - val_accuracy: 0.8761 - val_loss: 0.5343
Epoch 54/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9814 - loss: 0.0345 - val_accuracy: 0.8765 - val_loss: 0.5391
Epoch 55/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9818 - loss: 0.0322 - val_accuracy: 0.8773 - val_loss: 0.5400
Epoch 56/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9819 - loss: 0.0345 - val_accuracy: 0.8525 - val_loss: 0.6172
Epoch 57/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9802 - loss: 0.0391 - val_accuracy: 0.8698 - val_loss: 0.5334
Epoch 58/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9823 - loss: 0.0327 - val_accuracy: 0.8765 - val_loss: 0.5325
Epoch 59/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9805 - loss: 0.0356 - val_accuracy: 0.8772 - val_loss: 0.5345
Epoch 60/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9836 - loss: 0.0319 - val_accuracy: 0.8752 - val_loss: 0.5415
Epoch 61/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9820 - loss: 0.0326 - val_accuracy: 0.8720 - val_loss: 0.5537
Epoch 62/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9823 - loss: 0.0340 - val_accuracy: 0.8700 - val_loss: 0.5677
Epoch 63/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9820 - loss: 0.0337 - val_accuracy: 0.8694 - val_loss: 0.5614
Epoch 64/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9815 - loss: 0.0366 - val_accuracy: 0.8703 - val_loss: 0.5572
Epoch 65/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9818 - loss: 0.0349 - val_accuracy: 0.8749 - val_loss: 0.5443
Epoch 66/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9811 - loss: 0.0343 - val_accuracy: 0.8764 - val_loss: 0.5476
Epoch 67/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9833 - loss: 0.0317 - val_accuracy: 0.8697 - val_loss: 0.5709
Epoch 68/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9813 - loss: 0.0341 - val_accuracy: 0.8726 - val_loss: 0.5544
Epoch 69/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9814 - loss: 0.0333 - val_accuracy: 0.8719 - val_loss: 0.5630
Epoch 70/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9829 - loss: 0.0319 - val_accuracy: 0.8717 - val_loss: 0.5647
Epoch 71/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9823 - loss: 0.0324 - val_accuracy: 0.8628 - val_loss: 0.5948
Epoch 72/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9822 - loss: 0.0332 - val_accuracy: 0.8685 - val_loss: 0.5950
Epoch 73/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9812 - loss: 0.0346 - val_accuracy: 0.8611 - val_loss: 0.5981
Epoch 74/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9797 - loss: 0.0411 - val_accuracy: 0.8687 - val_loss: 0.5538
Epoch 75/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9819 - loss: 0.0344 - val_accuracy: 0.8720 - val_loss: 0.5525
Epoch 76/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9829 - loss: 0.0320 - val_accuracy: 0.8693 - val_loss: 0.5666
Epoch 77/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9829 - loss: 0.0320 - val_accuracy: 0.8736 - val_loss: 0.5615
Epoch 78/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9814 - loss: 0.0345 - val_accuracy: 0.8726 - val_loss: 0.5611
Epoch 79/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9824 - loss: 0.0326 - val_accuracy: 0.8696 - val_loss: 0.5769
Epoch 80/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9813 - loss: 0.0339 - val_accuracy: 0.8702 - val_loss: 0.5682
Epoch 81/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9814 - loss: 0.0334 - val_accuracy: 0.8699 - val_loss: 0.5913
Epoch 82/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9813 - loss: 0.0346 - val_accuracy: 0.8697 - val_loss: 0.5975
Epoch 83/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9812 - loss: 0.0360 - val_accuracy: 0.8651 - val_loss: 0.5846
Epoch 84/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9818 - loss: 0.0341 - val_accuracy: 0.8712 - val_loss: 0.5726
Epoch 85/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9829 - loss: 0.0323 - val_accuracy: 0.8752 - val_loss: 0.5704
Epoch 86/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9828 - loss: 0.0316 - val_accuracy: 0.8700 - val_loss: 0.5743
Epoch 87/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9828 - loss: 0.0321 - val_accuracy: 0.8709 - val_loss: 0.5806
Epoch 88/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9833 - loss: 0.0305 - val_accuracy: 0.8705 - val_loss: 0.5873
Epoch 89/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9819 - loss: 0.0339 - val_accuracy: 0.8686 - val_loss: 0.5893
Epoch 90/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9821 - loss: 0.0326 - val_accuracy: 0.8632 - val_loss: 0.5951
Epoch 91/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9795 - loss: 0.0405 - val_accuracy: 0.8739 - val_loss: 0.5708
Epoch 92/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9824 - loss: 0.0346 - val_accuracy: 0.8659 - val_loss: 0.5807
Epoch 93/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9836 - loss: 0.0320 - val_accuracy: 0.8676 - val_loss: 0.5979
Epoch 94/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9825 - loss: 0.0317 - val_accuracy: 0.8681 - val_loss: 0.5946
Epoch 95/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9817 - loss: 0.0336 - val_accuracy: 0.8694 - val_loss: 0.5903
Epoch 96/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9828 - loss: 0.0323 - val_accuracy: 0.8688 - val_loss: 0.6080
Epoch 97/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9815 - loss: 0.0324 - val_accuracy: 0.8712 - val_loss: 0.6066
Epoch 98/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9821 - loss: 0.0326 - val_accuracy: 0.8696 - val_loss: 0.6045
Epoch 99/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9827 - loss: 0.0322 - val_accuracy: 0.8727 - val_loss: 0.6091
Epoch 100/100
739/739 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.9816 - loss: 0.0344 - val_accuracy: 0.8567 - val_loss: 0.6535

In [144]:
import pickle

In [145]:
with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)

In [146]:
model_final.save('sentiment_analysis_model.h5')
model_final.save('sentiment_analysis_model.keras')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.