### Initialization

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('dataset.csv')
data.head()

                                                Text Language      Label
0  @Charlie_Corley @Kristine1G @amyklobuchar @Sty...       en  litigious
1  #BadBunny: Como dos gotas de agua: Joven se di...       es   negative
2  https://t.co/YJNiO0p1JV Flagstar Bank disclose...       en  litigious
3  Rwanda is set to host the headquarters of Unit...       en   positive
4  OOPS. I typed her name incorrectly (today’s br...       en  litigious

In [3]:
data.drop(columns=['Language'], inplace=True)

In [4]:
data.isnull().sum()

Text     0
Label    0
dtype: int64

In [5]:
data.drop_duplicates(inplace=True)

In [6]:
data.duplicated().sum()

0

In [7]:
data.rename(
    columns={
        'Label': 'Sentiment',
        'Text': 'Tweets'
    },
    inplace=True
)

In [8]:
data.head()

                                              Tweets  Sentiment
0  @Charlie_Corley @Kristine1G @amyklobuchar @Sty...  litigious
1  #BadBunny: Como dos gotas de agua: Joven se di...   negative
2  https://t.co/YJNiO0p1JV Flagstar Bank disclose...  litigious
3  Rwanda is set to host the headquarters of Unit...   positive
4  OOPS. I typed her name incorrectly (today’s br...  litigious

In [9]:
data = data[data['Sentiment'] !='uncertainty']

In [10]:
data.head()

                                              Tweets  Sentiment
0  @Charlie_Corley @Kristine1G @amyklobuchar @Sty...  litigious
1  #BadBunny: Como dos gotas de agua: Joven se di...   negative
2  https://t.co/YJNiO0p1JV Flagstar Bank disclose...  litigious
3  Rwanda is set to host the headquarters of Unit...   positive
4  OOPS. I typed her name incorrectly (today’s br...  litigious

In [11]:
data.shape

(726453, 2)

In [12]:
data['Sentiment'].value_counts()

Sentiment
positive     263178
negative     261049
litigious    202226
Name: count, dtype: int64

### Feature Encoding

In [13]:
import tensorflow as tf
from keras import backend as K
import gc

K.clear_session()
gc.collect()

2026-04-26 09:45:54.077726: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-04-26 09:45:54.091336: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1777176954.107001   27274 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1777176954.112456   27274 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-04-26 09:45:54.131590: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX_VNNI, in other operations, rebuild TensorFlow with the appropriate compiler flags.

0

In [14]:
gpus = tf.config.list_physical_devices('GPU')

if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("GPU is ready:", gpus)
    except RuntimeError as e:
        print(e)
else:
    print("No GPU found")

GPU is ready: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [15]:
gpus = tf.config.list_physical_devices('GPU')

if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        print("GPU is ready:", gpus)
    except RuntimeError as e:
        print(e)
else:
    print("No GPU found")

GPU is ready: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [16]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le = LabelEncoder()

In [19]:
data['Sentiment'] = le.fit_transform(data['Sentiment'])

In [20]:
data['Sentiment'].value_counts()

Sentiment
2    263178
1    261049
0    202226
Name: count, dtype: int64

In [21]:
from tensorflow import keras

In [22]:
Tokenizer = keras.preprocessing.text.Tokenizer

# tokenizer = Tokenizer()

### Here Keras Tokenizer is used to convert text into sequence of numbers. 
when we use tokenizer, it creates a dictionary of all the words in the text and assigns a unique number to each word. Then it converts the text into a sequence of numbers based on the dictionary.

- and also if new word comes in the test data which is not present in the training data, then it uses something called out of vocabulary token (OOV) to represent that word.
- Let's say : Hello, okay. is the training data. 
- Testing : amit --> OOV token --> treating as "Nothing" or "Unknown"

In [23]:
tokenizer = Tokenizer(oov_token="Nothing")

In [24]:
tokenizer.fit_on_texts(data['Tweets'])

In [25]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'and': 5,
 'of': 6,
 'is': 7,
 't': 8,
 'co': 9,
 'https': 10,
 'i': 11,
 'in': 12,
 'you': 13,
 'for': 14,
 'that': 15,
 'it': 16,
 'this': 17,
 'on': 18,
 'be': 19,
 'with': 20,
 'are': 21,
 'not': 22,
 'have': 23,
 'was': 24,
 'but': 25,
 'so': 26,
 'they': 27,
 'my': 28,
 'your': 29,
 'if': 30,
 'as': 31,
 'he': 32,
 'we': 33,
 'at': 34,
 'all': 35,
 'just': 36,
 'no': 37,
 'what': 38,
 'will': 39,
 'an': 40,
 'like': 41,
 'good': 42,
 'or': 43,
 'from': 44,
 'about': 45,
 'by': 46,
 'can': 47,
 'me': 48,
 'do': 49,
 'people': 50,
 'amp': 51,
 'one': 52,
 'his': 53,
 'has': 54,
 'how': 55,
 'get': 56,
 'more': 57,
 'out': 58,
 'when': 59,
 'best': 60,
 'their': 61,
 'who': 62,
 'would': 63,
 'up': 64,
 'law': 65,
 'bad': 66,
 'she': 67,
 'wrong': 68,
 "it's": 69,
 'our': 70,
 'there': 71,
 'contract': 72,
 'legal': 73,
 'now': 74,
 'lost': 75,
 'poor': 76,
 'them': 77,
 'excited': 78,
 'perfect': 79,
 'her': 80,
 'criminal': 81,
 'settlement': 82,
 'it’s': 83,
 'improve': 84,
 'easier': 85,
 'incredible': 86,
 'witness': 87,
 'know': 88,
 'flawed': 89,
 'time': 90,
 'been': 91,
 'think': 92,
 'breach': 93,
 'broken': 94,
 'because': 95,
 'de': 96,
 'had': 97,
 'him': 98,
 'innovation': 99,
 'problem': 100,
 'why': 101,
 'make': 102,
 'accident': 103,
 'see': 104,
 'even': 105,
 'than': 106,
 'some': 107,
 'question': 108,
 'only': 109,
 'us': 110,
 "i'm": 111,
 "don't": 112,
 'were': 113,
 'right': 114,
 'i’m': 115,
 'then': 116,
 'should': 117,
 'being': 118,
 'new': 119,
 'want': 120,
 'still': 121,
 'much': 122,
 'go': 123,
 'way': 124,
 'too': 125,
 'also': 126,
 'did': 127,
 'any': 128,
 'need': 129,
 '2': 130,
 'really': 131,
 'dream': 132,
 '1': 133,
 'don’t': 134,
 'very': 135,
 'after': 136,
 'into': 137,
 'never': 138,
 'got': 139,
 'life': 140,
 'could': 141,
 'these': 142,
 'trump': 143,
 'going': 144,
 'over': 145,
 'back': 146,
 'here': 147,
 'other': 148,
 'day': 149,
 'which': 150,
 'say': 151,
 'love': 152,
 'said': 153,
 'its': 154,
 'many': 155,
 'well': 156,
 'first': 157,
 'take': 158,
 '3': 159,
 'que': 160,
 'work': 161,
 'am': 162,
 'years': 163,
 'those': 164,
 'la': 165,
 'most': 166,
 'where': 167,
 'year': 168,
 'today': 169,
 'better': 170,
 'always': 171,
 'things': 172,
 'made': 173,
 'every': 174,
 'man': 175,
 'thing': 176,
 'something': 177,
 'u': 178,
 'same': 179,
 'does': 180,
 'before': 181,
 "that's": 182,
 'help': 183,
 'down': 184,
 'great': 185,
 'last': 186,
 'off': 187,
 'ever': 188,
 'world': 189,
 'look': 190,
 'someone': 191,
 'nothing': 192,
 'come': 193,
 'that’s': 194,
 'again': 195,
 '6': 196,
 'court': 197,
 'team': 198,
 'feel': 199,
 'hope': 200,
 'sure': 201,
 'actually': 202,
 'money': 203,
 'lot': 204,
 'game': 205,
 "you're": 206,
 'dreams': 207,
 '5': 208,
 'getting': 209,
 'keep': 210,
 'against': 211,
 'questions': 212,
 'own': 213,
 'yes': 214,
 'abortion': 215,
 'system': 216,
 'lol': 217,
 'doing': 218,
 'part': 219,
 "can't": 220,
 'next': 221,
 'under': 222,
 'long': 223,
 '4': 224,
 'done': 225,
 'use': 226,
 'person': 227,
 'another': 228,
 'while': 229,
 'real': 230,
 'makes': 231,
 'anything': 232,
 'state': 233,
 'such': 234,
 'give': 235,
 'may': 236,
 'through': 237,
 'two': 238,
 'big': 239,
 'care': 240,
 'find': 241,
 'already': 242,
 'en': 243,
 'point': 244,
 'believe': 245,
 'stop': 246,
 'everyone': 247,
 'women': 248,
 'both': 249,
 'can’t': 250,
 'since': 251,
 'trying': 252,
 'read': 253,
 'problems': 254,
 'country': 255,
 'please': 256,
 'you’re': 257,
 'y': 258,
 'without': 259,
 'live': 260,
 'news': 261,
 'let': 262,
 'thank': 263,
 '”': 264,
 'oh': 265,
 'having': 266,
 'making': 267,
 'im': 268,
 'everything': 269,
 'e': 270,
 'maybe': 271,
 'saying': 272,
 'support': 273,
 'show': 274,
 'un': 275,
 'end': 276,
 'little': 277,
 'free': 278,
 "didn't": 279,
 'shit': 280,
 'data': 281,
 'he’s': 282,
 'around': 283,
 'mean': 284,
 'play': 285,
 'government': 286,
 'god': 287,
 'put': 288,
 'tell': 289,
 '10': 290,
 'might': 291,
 "doesn't": 292,
 'pay': 293,
 'o': 294,
 'anyone': 295,
 'must': 296,
 'though': 297,
 'old': 298,
 'security': 299,
 'hard': 300,
 'via': 301,
 'try': 302,
 'thought': 303,
 'case': 304,
 'job': 305,
 'enough': 306,
 '2022': 307,
 'yet': 308,
 'start': 309,
 'el': 310,
 'away': 311,
 'rights': 312,
 'true': 313,
 'left': 314,
 'family': 315,
 'days': 316,
 'didn’t': 317,
 "he's": 318,
 'understand': 319,
 'yeah': 320,
 'change': 321,
 'happy': 322,
 'says': 323,
 'guy': 324,
 'until': 325,
 'health': 326,
 'looking': 327,
 'needs': 328,
 'ask': 329,
 'used': 330,
 "i've": 331,
 'probably': 332,
 'far': 333,
 'power': 334,
 'home': 335,
 'doesn’t': 336,
 'business': 337,
 'place': 338,
 'few': 339,
 'gonna': 340,
 'human': 341,
 'call': 342,
 'learn': 343,
 'answer': 344,
 "isn't": 345,
 'car': 346,
 'literally': 347,
 'kids': 348,
 'once': 349,
 'season': 350,
 'pretty': 351,
 'watch': 352,
 'states': 353,
 'night': 354,
 'full': 355,
 'week': 356,
 'between': 357,
 'times': 358,
 'morning': 359,
 'wait': 360,
 'police': 361,
 'testimony': 362,
 'million': 363,
 'cause': 364,
 'future': 365,
 'white': 366,
 'w': 367,
 'coming': 368,
 'fact': 369,
 'i’ve': 370,
 'school': 371,
 'public': 372,
 'whole': 373,
 '😂': 374,
 'looks': 375,
 'working': 376,
 'sorry': 377,
 'le': 378,
 'told': 379,
 'tampering': 380,
 'se': 381,
 'top': 382,
 'house': 383,
 'es': 384,
 'thanks': 385,
 'evidence': 386,
 'party': 387,
 'different': 388,
 'happen': 389,
 'eu': 390,
 'president': 391,
 'service': 392,
 'reason': 393,
 'men': 394,
 'woman': 395,
 'story': 396,
 'others': 397,
 'wanted': 398,
 'gets': 399,
 'guys': 400,
 'baby': 401,
 'else': 402,
 'vote': 403,
 'least': 404,
 's': 405,
 'agree': 406,
 'either': 407,
 'check': 408,
 'high': 409,
 'heart': 410,
 'less': 411,
 'seems': 412,
 'hearing': 413,
 'isn’t': 414,
 'hear': 415,
 'absolutely': 416,
 'seen': 417,
 '7': 418,
 'heard': 419,
 'during': 420,
 'using': 421,
 'talk': 422,
 'knew': 423,
 'due': 424,
 'based': 425,
 'mind': 426,
 'accidents': 427,
 'et': 428,
 'etc': 429,
 'amazing': 430,
 'went': 431,
 "there's": 432,
 'able': 433,
 'friends': 434,
 'idea': 435,
 'child': 436,
 'player': 437,
 'children': 438,
 'side': 439,
 'yourself': 440,
 'means': 441,
 'decision': 442,
 'remember': 443,
 'friend': 444,
 'matter': 445,
 'found': 446,
 'deal': 447,
 'fucking': 448,
 'win': 449,
 'called': 450,
 'move': 451,
 'name': 452,
 'open': 453,
 'instead': 454,
 'video': 455,
 'control': 456,
 'talking': 457,
 'thinking': 458,
 'set': 459,
 'ok': 460,
 "they're": 461,
 'each': 462,
 'happened': 463,
 'justice': 464,
 'ago': 465,
 'media': 466,
 'hate': 467,
 'twitter': 468,
 'experience': 469,
 'committee': 470,
 'run': 471,
 'social': 472,
 'laws': 473,
 'wants': 474,
 'kind': 475,
 'post': 476,
 'almost': 477,
 'games': 478,
 'players': 479,
 'taking': 480,
 'black': 481,
 'uk': 482,
 'order': 483,
 'act': 484,
 'bit': 485,
 'share': 486,
 'issue': 487,
 'gt': 488,
 'stuff': 489,
 'lives': 490,
 'war': 491,
 'stay': 492,
 'guess': 493,
 'hearsay': 494,
 'definitely': 495,
 'd': 496,
 'wish': 497,
 '100': 498,
 'head': 499,
 '20': 500,
 'roe': 501,
 'community': 502,
 'n': 503,
 'face': 504,
 "we're": 505,
 '8': 506,
 'sign': 507,
 'fun': 508,
 'bc': 509,
 'city': 510,
 'action': 511,
 'took': 512,
 'course': 513,
 'join': 514,
 'important': 515,
 'asked': 516,
 'line': 517,
 'sense': 518,
 'playing': 519,
 'girl': 520,
 'innovations': 521,
 'à': 522,
 'les': 523,
 'leave': 524,
 'x': 525,
 'technology': 526,
 'die': 527,
 'comes': 528,
 'history': 529,
 'soon': 530,
 'na': 531,
 'become': 532,
 'living': 533,
 '😭': 534,
 'é': 535,
 'crime': 536,
 'together': 537,
 'exactly': 538,
 'truth': 539,
 'jan': 540,
 'came': 541,
 'choice': 542,
 'super': 543,
 'especially': 544,
 'traffic': 545,
 'there’s': 546,
 'art': 547,
 'capitol': 548,
 'tweet': 549,
 'nice': 550,
 'book': 551,
 "won't": 552,
 'they’re': 553,
 'election': 554,
 'america': 555,
 '30': 556,
 'myself': 557,
 'level': 558,
 'american': 559,
 'political': 560,
 'saw': 561,
 'young': 562,
 'hand': 563,
 'months': 564,
 'past': 565,
 'luck': 566,
 'logic': 567,
 'food': 568,
 'rest': 569,
 'sad': 570,
 'process': 571,
 'bring': 572,
 'cannot': 573,
 'por': 574,
 'tried': 575,
 'follow': 576,
 'possible': 577,
 'second': 578,
 'constitution': 579,
 'body': 580,
 'project': 581,
 'b': 582,
 'gop': 583,
 'argument': 584,
 'given': 585,
 'buy': 586,
 'rather': 587,
 'class': 588,
 'judiciarygop': 589,
 'plus': 590,
 'biden': 591,
 'sweet': 592,
 'fuck': 593,
 'v': 594,
 'asking': 595,
 'non': 596,
 'company': 597,
 'dont': 598,
 'death': 599,
 'ones': 600,
 'started': 601,
 'break': 602,
 '0': 603,
 'june': 604,
 'trust': 605,
 'watching': 606,
 'single': 607,
 'finally': 608,
 'clear': 609,
 'ur': 610,
 'market': 611,
 '–': 612,
 'c': 613,
 'issues': 614,
 'goes': 615,
 'summer': 616,
 'los': 617,
 'hutchinson': 618,
 "she's": 619,
 'self': 620,
 'boy': 621,
 'building': 622,
 'ass': 623,
 'paid': 624,
 "wasn't": 625,
 'continue': 626,
 'pro': 627,
 'completely': 628,
 'easy': 629,
 'forward': 630,
 "i'll": 631,
 'former': 632,
 'three': 633,
 'fight': 634,
 'beautiful': 635,
 'close': 636,
 'words': 637,
 'federal': 638,
 'opinion': 639,
 'listen': 640,
 'knows': 641,
 'hit': 642,
 'imagine': 643,
 'wow': 644,
 'song': 645,
 'she’s': 646,
 '50': 647,
 'covid': 648,
 'plan': 649,
 'chance': 650,
 'wanna': 651,
 '9': 652,
 'research': 653,
 "what's": 654,
 'likely': 655,
 'sounds': 656,
 'bts': 657,
 'tech': 658,
 'access': 659,
 'supreme': 660,
 'group': 661,
 'quality': 662,
 'sometimes': 663,
 'music': 664,
 'small': 665,
 'serious': 666,
 'july': 667,
 'democracy': 668,
 'hell': 669,
 'term': 670,
 'huge': 671,
 'des': 672,
 'son': 673,
 'seeing': 674,
 '000': 675,
 'office': 676,
 'gun': 677,
 'giving': 678,
 'r': 679,
 'ppl': 680,
 'entire': 681,
 'damn': 682,
 'miss': 683,
 'information': 684,
 'space': 685,
 'honestly': 686,
 'we’re': 687,
 'ways': 688,
 '15': 689,
 'personal': 690,
 'tomorrow': 691,
 'what’s': 692,
 'wasn’t': 693,
 'signed': 694,
 "i'd": 695,
 'illegal': 696,
 'okay': 697,
 '—': 698,
 'smart': 699,
 'da': 700,
 'energy': 701,
 'half': 702,
 'won’t': 703,
 'ya': 704,
 'themselves': 705,
 'international': 706,
 'con': 707,
 'report': 708,
 '12': 709,
 'russia': 710,
 'sex': 711,
 'trial': 712,
 '…': 713,
 'secret': 714,
 'ready': 715,
 'worth': 716,
 'allowed': 717,
 'takes': 718,
 'price': 719,
 'month': 720,
 'cassidy': 721,
 'stand': 722,
 'lmao': 723,
 'needed': 724,
 'road': 725,
 'current': 726,
 'fix': 727,
 'gave': 728,
 'offer': 729,
 'works': 730,
 'safe': 731,
 'education': 732,
 'breaking': 733,
 'behind': 734,
 'hold': 735,
 'kill': 736,
 'moment': 737,
 'q': 738,
 'bro': 739,
 'i’ll': 740,
 'worse': 741,
 'number': 742,
 'digital': 743,
 'lo': 744,
 'hey': 745,
 'water': 746,
 'para': 747,
 'rule': 748,
 'judge': 749,
 'gone': 750,
 'não': 751,
 'clearly': 752,
 'event': 753,
 'word': 754,
 'oath': 755,
 'star': 756,
 'stupid': 757,
 'rich': 758,
 'turn': 759,
 'mark': 760,
 'list': 761,
 'movie': 762,
 "wouldn't": 763,
 'fine': 764,
 'actual': 765,
 'weeks': 766,
 'example': 767,
 'medical': 768,
 'fans': 769,
 'truly': 770,
 'youtube': 771,
 'red': 772,
 'across': 773,
 'dead': 774,
 'played': 775,
 'situation': 776,
 'lie': 777,
 'simple': 778,
 'shows': 779,
 'simply': 780,
 'happens': 781,
 'proud': 782,
 'hours': 783,
 'add': 784,
 'trade': 785,
 'taken': 786,
 "let's": 787,
 'si': 788,
 'later': 789,
 'ukraine': 790,
 'character': 791,
 'series': 792,
 'account': 793,
 'whether': 794,
 'republicans': 795,
 'record': 796,
 'seem': 797,
 'however': 798,
 'tho': 799,
 'members': 800,
 'club': 801,
 'feeling': 802,
 'value': 803,
 'services': 804,
 'nobody': 805,
 'risk': 806,
 'scotus': 807,
 'lead': 808,
 'build': 809,
 'whatever': 810,
 'al': 811,
 'wonder': 812,
 'worst': 813,
 'general': 814,
 'cool': 815,
 'create': 816,
 'lose': 817,
 'national': 818,
 'unless': 819,
 'per': 820,
 'surprise': 821,
 'sleep': 822,
 'protect': 823,
 'reality': 824,
 'y’all': 825,
 'waiting': 826,
 'often': 827,
 'democrats': 828,
 'save': 829,
 'pas': 830,
 'rules': 831,
 'room': 832,
 'killed': 833,
 'phone': 834,
 'telling': 835,
 'reported': 836,
 'seriously': 837,
 'glad': 838,
 'within': 839,
 'quite': 840,
 'omg': 841,
 'abortions': 842,
 'protection': 843,
 'including': 844,
 'lawyer': 845,
 "aren't": 846,
 'reading': 847,
 'low': 848,
 'agreement': 849,
 'fair': 850,
 'along': 851,
 'feels': 852,
 'speak': 853,
 'm': 854,
 'running': 855,
 'je': 856,
 'crazy': 857,
 'match': 858,
 'age': 859,
 'himself': 860,
 'kid': 861,
 'parents': 862,
 'king': 863,
 'ai': 864,
 'amount': 865,
 'pour': 866,
 'key': 867,
 'mental': 868,
 'fan': 869,
 'early': 870,
 'above': 871,
 'meet': 872,
 'vs': 873,
 'una': 874,
 'latest': 875,
 'staff': 876,
 'special': 877,
 'um': 878,
 'involved': 879,
 'i’d': 880,
 'opportunity': 881,
 'won': 882,
 'united': 883,
 'position': 884,
 'lt': 885,
 'drive': 886,
 'cases': 887,
 'interesting': 888,
 'dude': 889,
 'alone': 890,
 'mais': 891,
 'force': 892,
 '❤️': 893,
 'religion': 894,
 'del': 895,
 'respect': 896,
 'enjoy': 897,
 'congress': 898,
 'mr': 899,
 'funny': 900,
 'majority': 901,
 'com': 902,
 'final': 903,
 '🤣': 904,
 'society': 905,
 'dr': 906,
 '25': 907,
 'hands': 908,
 'bill': 909,
 'outside': 910,
 'wouldn’t': 911,
 'charges': 912,
 'eyes': 913,
 'claim': 914,
 'mother': 915,
 'meadows': 916,
 'official': 917,
 'cost': 918,
 'online': 919,
 'short': 920,
 'area': 921,
 'violence': 922,
 'defense': 923,
 'wall': 924,
 'potus': 925,
 'link': 926,
 'attack': 927,
 'lies': 928,
 'type': 929,
 'prove': 930,
 'murder': 931,
 'hurt': 932,
 'industry': 933,
 'science': 934,
 'global': 935,
 'send': 936,
 'countries': 937,
 'local': 938,
 'beyond': 939,
 'policy': 940,
 'focus': 941,
 'strong': 942,
 'article': 943,
 'peace': 944,
 'lying': 945,
 'potential': 946,
 'career': 947,
 'near': 948,
 'reach': 949,
 'enforcement': 950,
 'twt': 951,
 'tonight': 952,
 'totally': 953,
 'step': 954,
 'longer': 955,
 'anyway': 956,
 'mas': 957,
 'pass': 958,
 'forget': 959,
 '28': 960,
 'tv': 961,
 'allow': 962,
 'land': 963,
 'tax': 964,
 'nft': 965,
 'statement': 966,
 'main': 967,
 'role': 968,
 'learning': 969,
 'design': 970,
 'choose': 971,
 'available': 972,
 'aren’t': 973,
 'happening': 974,
 "you've": 975,
 'blue': 976,
 'major': 977,
 'idk': 978,
 'calling': 979,
 'let’s': 980,
 'sport': 981,
 'companies': 982,
 'obviously': 983,
 'blame': 984,
 'fire': 985,
 'front': 986,
 'couple': 987,
 'testify': 988,
 'felt': 989,
 'solution': 990,
 'terms': 991,
 'j': 992,
 'fall': 993,
 'du': 994,
 'fit': 995,
 'development': 996,
 'voting': 997,
 'sound': 998,
 'pick': 999,
 'provide': 1000,
 ...}

In [26]:
tokenizer.word_counts

OrderedDict([('charlie', 475),
             ('corley', 2),
             ('kristine1g', 1),
             ('amyklobuchar', 62),
             ('stylewriternyc', 1),
             ('testimony', 5276),
             ('is', 254403),
             ('not', 98284),
             ('evidence', 5026),
             ('in', 217980),
             ('a', 374464),
             ('court', 10234),
             ('of', 274977),
             ('law', 36455),
             ('state', 8716),
             ('or', 51373),
             ('federal', 2961),
             ('must', 6780),
             ('stand', 2660),
             ('up', 36794),
             ('to', 457704),
             ('cross', 1645),
             ('examination', 510),
             ('badbunny', 4),
             ('como', 1730),
             ('dos', 503),
             ('gotas', 2),
             ('de', 27550),
             ('agua', 39),
             ('joven', 18),
             ('se', 5082),
             ('disfraza', 1),
             ('bad', 36366),
             ('bunny', 671),
             ('y', 7939),
             ('causa', 82),
             ('tumulto', 1),
             ('en', 8500),
             ('alfombra', 1),
             ('roja', 11),
             ('https', 246213),
             ('t', 250488),
             ('co', 249301),
             ('3524seangh', 1),
             ('yjnio0p1jv', 1),
             ('flagstar', 410),
             ('bank', 1809),
             ('discloses', 111),
             ('data', 7153),
             ('breach', 28944),
             ('that', 166964),
             ('impacted', 275),
             ('1', 18187),
             ('5', 9486),
             ('million', 5271),
             ('individuals', 812),
             ('cybersecurity', 1207),
             ('rwanda', 164),
             ('set', 4184),
             ('host', 746),
             ('the', 633100),
             ('headquarters', 62),
             ('united', 2148),
             ('nations', 508),
             ('development', 1909),
             ('programme’s', 1),
             ('undp', 23),
             ('new', 21235),
             ('innovation', 26211),
             ('financing', 213),
             ('facility', 318),
             ('find', 8532),
             ('out', 38786),
             ('more', 39990),
             ('bznktc8pl0', 1),
             ('sovereigngroup', 1),
             ('sovereignafrica', 1),
             ('oops', 211),
             ('i', 233149),
             ('typed', 71),
             ('her', 30576),
             ('name', 4246),
             ('incorrectly', 63),
             ('today’s', 829),
             ('brave', 728),
             ('witness', 29812),
             ('cassidyhutchinson', 417),
             ('6', 10514),
             ('premeditatedviolence', 1),
             ('7', 4728),
             ('probaby', 3),
             ('witnesstamperig', 1),
             ('don’t', 18136),
             ('forget', 1996),
             ('markmeadows', 299),
             ('requesting', 97),
             ('pardon', 831),
             ('trumpknew', 54),
             ('trumpcapitolcoupattack', 1),
             ('capitolcoupattempt', 1),
             ('neverforgetjanuary6th', 9),
             ('neverforgetjan6th', 1),
             ('oexm3hdwnz', 1),
             ('it', 164443),
             ('sucks', 878),
             ('for', 176076),
             ('me', 48749),
             ('since', 8233),
             ("i'm", 22385),
             ('focused', 696),
             ('on', 114739),
             ('nature', 1088),
             ('aspect', 353),
             ('things', 12891),
             ('but', 91004),
             ('environmental', 346),
             ('problems', 8115),
             ('we', 65492),
             ('have', 92857),
             ('all', 61909),
             ('their', 37750),
             ('roots', 143),
             ('social', 4034),
             ('economic', 1259),
             ('amp', 43339),
             ('political', 3387),
             ('issues', 3065),
             ('simply', 2463),
             ('recycling', 147),
             ('using', 4598),
             ('renewable', 125),
             ('energy', 2713),
             ('like', 52609),
             ('fixing', 449),
             ('top', 5082),
             ('floor', 772),
             ('building', 3018),
             ('with', 104414),
             ('an', 53272),
             ('unsteady', 4),
             ('foundation', 667),
             ('font', 162),
             ('treballar', 1),
             ('l’obra', 1),
             ('partir', 72),
             ('dels', 27),
             ('19', 1416),
             ('anys', 14),
             ('fins', 29),
             ('als', 368),
             ('50', 2921),
             ('també', 13),
             ('q', 2590),
             ('t’hagin', 1),
             ('jubilat', 1),
             ('degut', 1),
             ('un', 7386),
             ('accident', 24881),
             ('laboral', 25),
             ('…', 2692),
             ('crema', 11),
             ('mes', 219),
             ('el', 6500),
             ('“foc', 1),
             ('fogons”', 1),
             ('qualsevol', 7),
             ('cuina', 1),
             ('sobreportantlavida', 1),
             ('security', 6750),
             ('constant', 500),
             ('crises', 77),
             ('distract', 275),
             ('masses', 194),
             ('and', 336120),
             ('they', 81561),
             ('rob', 696),
             ('us', 23199),
             ('blind', 660),
             ('meantime', 119),
             ("it's", 33880),
             ('coming', 5245),
             ('at', 64485),
             ('american', 3388),
             ('people', 43701),
             ('breathtaking', 75),
             ('speed', 1049),
             ('every', 12708),
             ('direction', 872),
             ('til', 336),
             ("don't", 22264),
             ('know', 29456),
             ('where', 13808),
             ('look', 11005),
             ('first', 15101),
             ('filmthepolicela', 7),
             ('broken', 28515),
             ('rib', 46),
             ('can', 48850),
             ('puncture', 13),
             ('lung', 124),
             ('lead', 2383),
             ('collapsed', 108),
             ('both', 8295),
             ('much', 20373),
             ('longer', 2007),
             ('recoveries', 12),
             ('than', 24118),
             ('just', 59778),
             ('break', 3136),
             ('get', 41707),
             ('checked', 450),
             ('jacobringenwald', 2),
             ('akeithwatts', 2),
             ('countdankulatv', 76),
             ('agree', 4840),
             ('flawed', 29411),
             ('response', 1817),
             ('small', 2844),
             ('many', 15754),
             ('pl', 261),
             ('presume', 76),
             ('would', 37350),
             ('nuance', 136),
             ('understanding', 1503),
             ('needed', 2651),
             ('those', 14245),
             ('cases', 2144),
             ('good', 52318),
             ('starting', 1814),
             ('point', 8496),
             ('drink', 772),
             ('drive', 2146),
             ('play', 7069),
             ('guns', 1837),
             ('sound', 1905),
             ('advice', 1476),
             ('sounds', 2870),
             ('simplistic', 59),
             ('nevertheless', 86),
             ('true', 6365),
             ('nz', 194),
             ('hk', 49),
             ('su', 1419),
             ('telebusiness', 7),
             ('my', 79567),
             ('question', 23980),
             ('was', 92556),
             ('rhetorical', 177),
             ('russia', 2697),
             ('propping', 18),
             ('market', 3094),
             ('china', 1329),
             ('india', 1825),
             ('are', 101947),
             ('willing', 1437),
             ('pay', 6858),
             ('inflated', 80),
             ('gas', 1852),
             ('prices', 1147),
             ('further', 1774),
             ('aid', 817),
             ('wimbledon', 1116),
             ('nick', 396),
             ('kyrgios', 50),
             ('admits', 120),
             ('spitting', 50),
             ('towards', 1674),
             ("'disrespectful'", 2),
             ('spectator', 57),
             ('after', 17938),
             ('beating', 344),
             ('paul', 772),
             ('jubb', 39),
             ('jkfqhimlqw', 1),
             ('grief', 330),
             ('‼️‼️', 22),
             ('class', 3215),
             ('isn’t', 4754),
             ('he…', 5),
             ('booktwt', 16),
             ('thing', 12454),
             ('if', 67548),
             ('so', 89803),
             ('thats', 1884),
             ('she', 34695),
             ('speaks', 476),
             ('perfect', 30675),
             ('grammar', 190),
             ('spellinc', 1),
             ('punctuation', 32),
             ('capitalization', 7),
             ('everyones', 54),
             ('favlrite', 1),
             ('moot', 101),
             ('okafyriuv8', 1),
             ('saltburned', 1),
             ('when', 37804),
             ('sign', 3752),
             ('surrender', 112),
             ('comes', 3622),
             ('michael’s', 6),
             ('smile', 828),
             ('splits', 28),
             ('his', 42696),
             ('face', 3760),
             ('sharp', 195),
             ('knife', 229),
             ('through', 8662),
             ('flesh', 144),
             ('chill', 337),
             ('dean', 316),
             ('very', 17941),
             ('core', 838),
             ('he', 67244),
             ('were', 22020),
             ('this', 122462),
             ('ice', 726),
             ('cold', 812),
             ('existence', 521),
             ('its', 15954),
             ('archangel', 2),
             ('enjoyable', 156),
             ('time', 29244),
             ('»', 198),
             ('roipaee', 1),
             ('joe98100959', 1),
             ('formula1game', 42),
             ('redbullracing', 199),
             ('silverstoneuk', 18),
             ('wrote', 880),
             ('them', 30919),
             ('now', 31144),
             ('waiting', 2320),
             ("i've", 5930),
             ('lost', 31060),
             ('hope', 10009),
             ('fifa', 142),
             ('games', 3973),
             ('worked', 1815),
             ('year', 13767),
             ('🤩', 569),
             ('power', 5855),
             ('back', 17061),
             ('1855749', 1),
             ('north', 1380),
             ('vi', 306),
             ('ladysmith', 1),
             ('near', 2024),
             ('1000', 426),
             ('block', 1025),
             ('4th', 965),
             ('ave', 825),
             ('cause', 5270),
             ('motor', 397),
             ('vehicle', 1512),
             ('bchydro', 14),
             ('britishcolumbia', 10),
             ('canada', 1765),
             ('poweroutage', 7),
             ('poweron', 5),
             ('end', 7309),
             ('consume', 140),
             ('fictional', 109),
             ('stories', 1268),
             ('enjoy', 2133),
             ('seem', 2413),
             ('fair', 2261),
             ('personally', 1339),
             ('love', 16069),
             ('seeing', 2809),
             ('characters', 1429),
             ('going', 17394),
             ('trough', 21),
             ('lowest', 227),
             ('as', 67410),
             ('highest', 776),
             ('fucked', 877),
             ('stuff', 3894),
             ("doesn't", 6890),
             ('spoil', 80),
             ('enjoyment', 73),
             ('though', 6775),
             ('did', 19821),
             ('few', 5788),
             ('dreams', 9557),
             ('about', 49608),
             ('last', 11292),
             ('chapters', 74),
             ('pyx4a63c5u', 1),
             ('duranto', 1),
             ('express', 535),
             ('a1', 108),
             ('coach', 1602),
             ('ac', 356),
             ('working', 5135),
             ('properly', 642),
             ('12294', 1),
             ('prayagraj', 4),
             ('ltt', 4),
             ('passengers', 218),
             ('sweating', 89),
             ('food', 3341),
             ('dinner', 497),
             ('unimpressive', 9),
             ('please', 8056),
             ('improve', 30077),
             ('standards', 882),
             ('irctcofficial', 9),
             ('wu', 40),
             ('think', 29063),
             ('rude2complain', 1),
             ('services', 2393),
             ('excuse', 1077),
             ('natgeotravel', 2),
             ('bbc', 377),
             ('travel', 1339),
             ('railminindia', 25),
             ('westernrly', 2),
             ('w', 5249),
             ('terrence', 68),
             ('you', 195230),
             ('poor', 31056),
             ('man', 12492),
             ("couldn't", 1648),
             ('care', 8587),
             ('less', 4798),
             ('acroce66', 10),
             ('by', 49176),
             ('way', 20193),
             ('never', 17742),
             ('too', 19867),
             ('late', 1789),
             ('tell', 6991),
             ('truth', 3508),
             ('excellent', 1022),
             ('film', 1279),
             ('cast', 656),
             ('incredible', 30021),
             ('tension', 126),
             ('well', 15326),
             ('done', 8880),
             ('melodramatic', 4),
             ("i'd", 2729),
             ('say', 16222),
             ('8', 3754),
             ('jakesucky', 48),
             ('ab', 393),
             ('loop', 353),
             ('absolutely', 4732),
             ('wow', 2930),
             ('how', 41829),
             ('taysom', 2),
             ("he's", 6225),
             ('used', 5959),
             ('right', 22000),
             ('content', 1805),
             ('creators', 271),
             ('better', 13339),
             ('youtube', 2480),
             ('presentation', 288),
             ('blog', 787),
             ('podcast', 1225),
             ('video', 4232),
             ('keynote', 188),
             ('speech', 1144),
             ('influencer', 92),
             ('mm3nzdktsa', 1),
             ('your', 72400),
             ('fight', 2976),
             ('save', 2313),
             ('uk', 3940),
             ('from', 50895),
             ('liars', 319),
             ('cheats', 56),
             ('charlatans', 30),
             ('steve', 1035),
             ('bray', 236),
             ('crowdfunding', 46),
             ('fundrazr', 10),
             ('support', 7425),
             ('retweet', 283),
             ('direct', 1559),
             ("steve's", 19),
             ('legal', 31787),
             ('case', 6657),
             ('rgjhx7hjcu', 1),
             ('joycewhitevance', 405),
             ('thedemcoalition', 24),
             ('answered', 870),
             ('clearly', 2537),
             ('invoking', 62),
             ('5th', 1171),
             ('simple', 2469),
             ('especially', 3473),
             ('member', 1335),
             ('military', 1319),
             ('swear', 674),
             ('defend', 1117),
             ('our', 32879),
             ('constitution', 3271),
             ('anything', 8721),
             ('other', 16945),
             ('resounding', 14),
             ('yes', 9350),
             ('same', 12118),
             ('saying', 7427),
             ('hell', 2836),
             ('no', 55543),
             ('incriminated', 6),
             ('himself', 2226),
             ('disgraced', 63),
             ('uniform', 135),
             ('imo', 1565),
             ('trump', 17405),
             ('phuked', 1),
             ('let’s', 1947),
             ('see', 24418),
             ('any', 19785),
             ('republicans', 2417),
             ('grow', 1506),
             ('spine', 179),
             ('watching', 3108),
             ('26', 635),
             ('old', 6767),
             ('young', 3376),
             ('woman', 4918),
             ('show', 7391),
             ('courage', 628),
             ('doubtful', 49),
             ('🙄', 1113),
             ('kbradjstorm', 3),
             ('bro', 2586),
             ('katz', 20),
             ('actually', 9922),
             ('ridiculous', 954),
             ('johnbick1960', 1),
             ('bobsouer', 1),
             ('listened', 359),
             ('book', 3415),
             ('read', 8124),
             ('ai—interesting', 1),
             ('also', 19858),
             ('suffers', 138),
             ('problem', 25997),
             ('pronounced', 45),
             ('“grimace”', 1),
             ('“grim', 1),
             ('ace', 256),
             ('”', 7783),
             ('could', 17455),
             ('ai', 2204),
             ('readings', 50),
             ('textbooks', 23),
             ('being', 21260),
             ('useful', 558),
             ('huntersville', 3),
             ('nc', 238),
             ('73', 162),
             ('sam', 583),
             ('furr', 4),
             ('rd', 1643),
             ('between', 5358),
             ('mayes', 5),
             ('road', 2651),
             ('westmoreland', 6),
             ('traffic', 3469),
             ('fwt2jwrevt', 40),
             ('alitomorenoc', 53),
             ('mames', 5),
             ('ya', 2707),
             ('mejor', 180),
             ('lárgate', 8),
             ('del', 2135),
             ('pri', 55),
             ('deja', 80),
             ('estar', 208),
             ('hundiendo', 1),
             ('más', 914),
             ('al', 2376),
             ('partido', 144),
             ('militancia', 3),
             ('con', 2699),
             ('pendejadas', 3),
             ('esta', 464),
             ('esto', 297),
             ('que', 14653),
             ('propones', 3),
             ('ahora', 288),
             ('si', 2430),
             ('sería', 108),
             ('esté', 32),
             ('armado', 23),
             ('hasta', 271),
             ('los', 3058),
             ('dientes', 5),
             ('es', 5052),
             ('la', 14080),
             ('propuesta', 21),
             ('para', 2559),
             ('una', 2176),
             ('escalada', 2),
             ('armada', 27),
             ('sin', 830),
             ('sentido', 74),
             ('madeinfrance', 6),
             ('👩\u200d💻', 5),
             ('le', 5108),
             ('pepr', 1),
             ('cybersecurite', 20),
             ('est', 1817),
             ('lancé', 12),
             ('france', 732),
             ('permettant', 14),
             ('des', 2817),
             ('transferts', 2),
             ('savoirs', 2),
             ('et', 4470),
             ('technologiques', 19),
             ('entre', 417),
             ('industriels', 14),
             ('universités', 3),
             ('grandes', 60),
             ('écoles', 12),
             ('🕴️💻💶👉https', 1),
             ('wtldk4jao8', 1),
             ('curry', 213),
             ('making', 7637),
             ('48m', 2),
             ('off', 11207),
             ('ring', 664),
             ('mf', 437),
             ('living', 3570),
             ('dream😭😭😭😭', 1),
             ('bn6n5fnpsz', 1),
             ('bowtiedhandyman', 2),
             ('am', 14551),
             ('sinple', 2),
             ('man…truck', 1),
             ('tall', 200),
             ('truck', 893),
             ('loud', 661),
             ('makes', 8750),
             ('thoughts', 1469),
             ('head', 3793),
             ('go', 20282),
             ('away', 6463),
             ('while', 8770),
             ('realhfegelein', 2),
             ('dubbaewwteeeff', 3),
             ('peterdempsey92', 2),
             ('aoc', 1139),
             ('reason', 4932),
             ('europe', 1213),
             ('spend', 1390),
             ('money', 9901),
             ('these', 17449),
             ('low', 2265),

In [27]:
tokenizer.document_count

726453

In [28]:
len((tokenizer.word_index)) ## Vocabulary size

1052348

In [29]:
tokenizer.word_counts

OrderedDict([('charlie', 475),
             ('corley', 2),
             ('kristine1g', 1),
             ('amyklobuchar', 62),
             ('stylewriternyc', 1),
             ('testimony', 5276),
             ('is', 254403),
             ('not', 98284),
             ('evidence', 5026),
             ('in', 217980),
             ('a', 374464),
             ('court', 10234),
             ('of', 274977),
             ('law', 36455),
             ('state', 8716),
             ('or', 51373),
             ('federal', 2961),
             ('must', 6780),
             ('stand', 2660),
             ('up', 36794),
             ('to', 457704),
             ('cross', 1645),
             ('examination', 510),
             ('badbunny', 4),
             ('como', 1730),
             ('dos', 503),
             ('gotas', 2),
             ('de', 27550),
             ('agua', 39),
             ('joven', 18),
             ('se', 5082),
             ('disfraza', 1),
             ('bad', 36366),
             ('bunny', 671),
             ('y', 7939),
             ('causa', 82),
             ('tumulto', 1),
             ('en', 8500),
             ('alfombra', 1),
             ('roja', 11),
             ('https', 246213),
             ('t', 250488),
             ('co', 249301),
             ('3524seangh', 1),
             ('yjnio0p1jv', 1),
             ('flagstar', 410),
             ('bank', 1809),
             ('discloses', 111),
             ('data', 7153),
             ('breach', 28944),
             ('that', 166964),
             ('impacted', 275),
             ('1', 18187),
             ('5', 9486),
             ('million', 5271),
             ('individuals', 812),
             ('cybersecurity', 1207),
             ('rwanda', 164),
             ('set', 4184),
             ('host', 746),
             ('the', 633100),
             ('headquarters', 62),
             ('united', 2148),
             ('nations', 508),
             ('development', 1909),
             ('programme’s', 1),
             ('undp', 23),
             ('new', 21235),
             ('innovation', 26211),
             ('financing', 213),
             ('facility', 318),
             ('find', 8532),
             ('out', 38786),
             ('more', 39990),
             ('bznktc8pl0', 1),
             ('sovereigngroup', 1),
             ('sovereignafrica', 1),
             ('oops', 211),
             ('i', 233149),
             ('typed', 71),
             ('her', 30576),
             ('name', 4246),
             ('incorrectly', 63),
             ('today’s', 829),
             ('brave', 728),
             ('witness', 29812),
             ('cassidyhutchinson', 417),
             ('6', 10514),
             ('premeditatedviolence', 1),
             ('7', 4728),
             ('probaby', 3),
             ('witnesstamperig', 1),
             ('don’t', 18136),
             ('forget', 1996),
             ('markmeadows', 299),
             ('requesting', 97),
             ('pardon', 831),
             ('trumpknew', 54),
             ('trumpcapitolcoupattack', 1),
             ('capitolcoupattempt', 1),
             ('neverforgetjanuary6th', 9),
             ('neverforgetjan6th', 1),
             ('oexm3hdwnz', 1),
             ('it', 164443),
             ('sucks', 878),
             ('for', 176076),
             ('me', 48749),
             ('since', 8233),
             ("i'm", 22385),
             ('focused', 696),
             ('on', 114739),
             ('nature', 1088),
             ('aspect', 353),
             ('things', 12891),
             ('but', 91004),
             ('environmental', 346),
             ('problems', 8115),
             ('we', 65492),
             ('have', 92857),
             ('all', 61909),
             ('their', 37750),
             ('roots', 143),
             ('social', 4034),
             ('economic', 1259),
             ('amp', 43339),
             ('political', 3387),
             ('issues', 3065),
             ('simply', 2463),
             ('recycling', 147),
             ('using', 4598),
             ('renewable', 125),
             ('energy', 2713),
             ('like', 52609),
             ('fixing', 449),
             ('top', 5082),
             ('floor', 772),
             ('building', 3018),
             ('with', 104414),
             ('an', 53272),
             ('unsteady', 4),
             ('foundation', 667),
             ('font', 162),
             ('treballar', 1),
             ('l’obra', 1),
             ('partir', 72),
             ('dels', 27),
             ('19', 1416),
             ('anys', 14),
             ('fins', 29),
             ('als', 368),
             ('50', 2921),
             ('també', 13),
             ('q', 2590),
             ('t’hagin', 1),
             ('jubilat', 1),
             ('degut', 1),
             ('un', 7386),
             ('accident', 24881),
             ('laboral', 25),
             ('…', 2692),
             ('crema', 11),
             ('mes', 219),
             ('el', 6500),
             ('“foc', 1),
             ('fogons”', 1),
             ('qualsevol', 7),
             ('cuina', 1),
             ('sobreportantlavida', 1),
             ('security', 6750),
             ('constant', 500),
             ('crises', 77),
             ('distract', 275),
             ('masses', 194),
             ('and', 336120),
             ('they', 81561),
             ('rob', 696),
             ('us', 23199),
             ('blind', 660),
             ('meantime', 119),
             ("it's", 33880),
             ('coming', 5245),
             ('at', 64485),
             ('american', 3388),
             ('people', 43701),
             ('breathtaking', 75),
             ('speed', 1049),
             ('every', 12708),
             ('direction', 872),
             ('til', 336),
             ("don't", 22264),
             ('know', 29456),
             ('where', 13808),
             ('look', 11005),
             ('first', 15101),
             ('filmthepolicela', 7),
             ('broken', 28515),
             ('rib', 46),
             ('can', 48850),
             ('puncture', 13),
             ('lung', 124),
             ('lead', 2383),
             ('collapsed', 108),
             ('both', 8295),
             ('much', 20373),
             ('longer', 2007),
             ('recoveries', 12),
             ('than', 24118),
             ('just', 59778),
             ('break', 3136),
             ('get', 41707),
             ('checked', 450),
             ('jacobringenwald', 2),
             ('akeithwatts', 2),
             ('countdankulatv', 76),
             ('agree', 4840),
             ('flawed', 29411),
             ('response', 1817),
             ('small', 2844),
             ('many', 15754),
             ('pl', 261),
             ('presume', 76),
             ('would', 37350),
             ('nuance', 136),
             ('understanding', 1503),
             ('needed', 2651),
             ('those', 14245),
             ('cases', 2144),
             ('good', 52318),
             ('starting', 1814),
             ('point', 8496),
             ('drink', 772),
             ('drive', 2146),
             ('play', 7069),
             ('guns', 1837),
             ('sound', 1905),
             ('advice', 1476),
             ('sounds', 2870),
             ('simplistic', 59),
             ('nevertheless', 86),
             ('true', 6365),
             ('nz', 194),
             ('hk', 49),
             ('su', 1419),
             ('telebusiness', 7),
             ('my', 79567),
             ('question', 23980),
             ('was', 92556),
             ('rhetorical', 177),
             ('russia', 2697),
             ('propping', 18),
             ('market', 3094),
             ('china', 1329),
             ('india', 1825),
             ('are', 101947),
             ('willing', 1437),
             ('pay', 6858),
             ('inflated', 80),
             ('gas', 1852),
             ('prices', 1147),
             ('further', 1774),
             ('aid', 817),
             ('wimbledon', 1116),
             ('nick', 396),
             ('kyrgios', 50),
             ('admits', 120),
             ('spitting', 50),
             ('towards', 1674),
             ("'disrespectful'", 2),
             ('spectator', 57),
             ('after', 17938),
             ('beating', 344),
             ('paul', 772),
             ('jubb', 39),
             ('jkfqhimlqw', 1),
             ('grief', 330),
             ('‼️‼️', 22),
             ('class', 3215),
             ('isn’t', 4754),
             ('he…', 5),
             ('booktwt', 16),
             ('thing', 12454),
             ('if', 67548),
             ('so', 89803),
             ('thats', 1884),
             ('she', 34695),
             ('speaks', 476),
             ('perfect', 30675),
             ('grammar', 190),
             ('spellinc', 1),
             ('punctuation', 32),
             ('capitalization', 7),
             ('everyones', 54),
             ('favlrite', 1),
             ('moot', 101),
             ('okafyriuv8', 1),
             ('saltburned', 1),
             ('when', 37804),
             ('sign', 3752),
             ('surrender', 112),
             ('comes', 3622),
             ('michael’s', 6),
             ('smile', 828),
             ('splits', 28),
             ('his', 42696),
             ('face', 3760),
             ('sharp', 195),
             ('knife', 229),
             ('through', 8662),
             ('flesh', 144),
             ('chill', 337),
             ('dean', 316),
             ('very', 17941),
             ('core', 838),
             ('he', 67244),
             ('were', 22020),
             ('this', 122462),
             ('ice', 726),
             ('cold', 812),
             ('existence', 521),
             ('its', 15954),
             ('archangel', 2),
             ('enjoyable', 156),
             ('time', 29244),
             ('»', 198),
             ('roipaee', 1),
             ('joe98100959', 1),
             ('formula1game', 42),
             ('redbullracing', 199),
             ('silverstoneuk', 18),
             ('wrote', 880),
             ('them', 30919),
             ('now', 31144),
             ('waiting', 2320),
             ("i've", 5930),
             ('lost', 31060),
             ('hope', 10009),
             ('fifa', 142),
             ('games', 3973),
             ('worked', 1815),
             ('year', 13767),
             ('🤩', 569),
             ('power', 5855),
             ('back', 17061),
             ('1855749', 1),
             ('north', 1380),
             ('vi', 306),
             ('ladysmith', 1),
             ('near', 2024),
             ('1000', 426),
             ('block', 1025),
             ('4th', 965),
             ('ave', 825),
             ('cause', 5270),
             ('motor', 397),
             ('vehicle', 1512),
             ('bchydro', 14),
             ('britishcolumbia', 10),
             ('canada', 1765),
             ('poweroutage', 7),
             ('poweron', 5),
             ('end', 7309),
             ('consume', 140),
             ('fictional', 109),
             ('stories', 1268),
             ('enjoy', 2133),
             ('seem', 2413),
             ('fair', 2261),
             ('personally', 1339),
             ('love', 16069),
             ('seeing', 2809),
             ('characters', 1429),
             ('going', 17394),
             ('trough', 21),
             ('lowest', 227),
             ('as', 67410),
             ('highest', 776),
             ('fucked', 877),
             ('stuff', 3894),
             ("doesn't", 6890),
             ('spoil', 80),
             ('enjoyment', 73),
             ('though', 6775),
             ('did', 19821),
             ('few', 5788),
             ('dreams', 9557),
             ('about', 49608),
             ('last', 11292),
             ('chapters', 74),
             ('pyx4a63c5u', 1),
             ('duranto', 1),
             ('express', 535),
             ('a1', 108),
             ('coach', 1602),
             ('ac', 356),
             ('working', 5135),
             ('properly', 642),
             ('12294', 1),
             ('prayagraj', 4),
             ('ltt', 4),
             ('passengers', 218),
             ('sweating', 89),
             ('food', 3341),
             ('dinner', 497),
             ('unimpressive', 9),
             ('please', 8056),
             ('improve', 30077),
             ('standards', 882),
             ('irctcofficial', 9),
             ('wu', 40),
             ('think', 29063),
             ('rude2complain', 1),
             ('services', 2393),
             ('excuse', 1077),
             ('natgeotravel', 2),
             ('bbc', 377),
             ('travel', 1339),
             ('railminindia', 25),
             ('westernrly', 2),
             ('w', 5249),
             ('terrence', 68),
             ('you', 195230),
             ('poor', 31056),
             ('man', 12492),
             ("couldn't", 1648),
             ('care', 8587),
             ('less', 4798),
             ('acroce66', 10),
             ('by', 49176),
             ('way', 20193),
             ('never', 17742),
             ('too', 19867),
             ('late', 1789),
             ('tell', 6991),
             ('truth', 3508),
             ('excellent', 1022),
             ('film', 1279),
             ('cast', 656),
             ('incredible', 30021),
             ('tension', 126),
             ('well', 15326),
             ('done', 8880),
             ('melodramatic', 4),
             ("i'd", 2729),
             ('say', 16222),
             ('8', 3754),
             ('jakesucky', 48),
             ('ab', 393),
             ('loop', 353),
             ('absolutely', 4732),
             ('wow', 2930),
             ('how', 41829),
             ('taysom', 2),
             ("he's", 6225),
             ('used', 5959),
             ('right', 22000),
             ('content', 1805),
             ('creators', 271),
             ('better', 13339),
             ('youtube', 2480),
             ('presentation', 288),
             ('blog', 787),
             ('podcast', 1225),
             ('video', 4232),
             ('keynote', 188),
             ('speech', 1144),
             ('influencer', 92),
             ('mm3nzdktsa', 1),
             ('your', 72400),
             ('fight', 2976),
             ('save', 2313),
             ('uk', 3940),
             ('from', 50895),
             ('liars', 319),
             ('cheats', 56),
             ('charlatans', 30),
             ('steve', 1035),
             ('bray', 236),
             ('crowdfunding', 46),
             ('fundrazr', 10),
             ('support', 7425),
             ('retweet', 283),
             ('direct', 1559),
             ("steve's", 19),
             ('legal', 31787),
             ('case', 6657),
             ('rgjhx7hjcu', 1),
             ('joycewhitevance', 405),
             ('thedemcoalition', 24),
             ('answered', 870),
             ('clearly', 2537),
             ('invoking', 62),
             ('5th', 1171),
             ('simple', 2469),
             ('especially', 3473),
             ('member', 1335),
             ('military', 1319),
             ('swear', 674),
             ('defend', 1117),
             ('our', 32879),
             ('constitution', 3271),
             ('anything', 8721),
             ('other', 16945),
             ('resounding', 14),
             ('yes', 9350),
             ('same', 12118),
             ('saying', 7427),
             ('hell', 2836),
             ('no', 55543),
             ('incriminated', 6),
             ('himself', 2226),
             ('disgraced', 63),
             ('uniform', 135),
             ('imo', 1565),
             ('trump', 17405),
             ('phuked', 1),
             ('let’s', 1947),
             ('see', 24418),
             ('any', 19785),
             ('republicans', 2417),
             ('grow', 1506),
             ('spine', 179),
             ('watching', 3108),
             ('26', 635),
             ('old', 6767),
             ('young', 3376),
             ('woman', 4918),
             ('show', 7391),
             ('courage', 628),
             ('doubtful', 49),
             ('🙄', 1113),
             ('kbradjstorm', 3),
             ('bro', 2586),
             ('katz', 20),
             ('actually', 9922),
             ('ridiculous', 954),
             ('johnbick1960', 1),
             ('bobsouer', 1),
             ('listened', 359),
             ('book', 3415),
             ('read', 8124),
             ('ai—interesting', 1),
             ('also', 19858),
             ('suffers', 138),
             ('problem', 25997),
             ('pronounced', 45),
             ('“grimace”', 1),
             ('“grim', 1),
             ('ace', 256),
             ('”', 7783),
             ('could', 17455),
             ('ai', 2204),
             ('readings', 50),
             ('textbooks', 23),
             ('being', 21260),
             ('useful', 558),
             ('huntersville', 3),
             ('nc', 238),
             ('73', 162),
             ('sam', 583),
             ('furr', 4),
             ('rd', 1643),
             ('between', 5358),
             ('mayes', 5),
             ('road', 2651),
             ('westmoreland', 6),
             ('traffic', 3469),
             ('fwt2jwrevt', 40),
             ('alitomorenoc', 53),
             ('mames', 5),
             ('ya', 2707),
             ('mejor', 180),
             ('lárgate', 8),
             ('del', 2135),
             ('pri', 55),
             ('deja', 80),
             ('estar', 208),
             ('hundiendo', 1),
             ('más', 914),
             ('al', 2376),
             ('partido', 144),
             ('militancia', 3),
             ('con', 2699),
             ('pendejadas', 3),
             ('esta', 464),
             ('esto', 297),
             ('que', 14653),
             ('propones', 3),
             ('ahora', 288),
             ('si', 2430),
             ('sería', 108),
             ('esté', 32),
             ('armado', 23),
             ('hasta', 271),
             ('los', 3058),
             ('dientes', 5),
             ('es', 5052),
             ('la', 14080),
             ('propuesta', 21),
             ('para', 2559),
             ('una', 2176),
             ('escalada', 2),
             ('armada', 27),
             ('sin', 830),
             ('sentido', 74),
             ('madeinfrance', 6),
             ('👩\u200d💻', 5),
             ('le', 5108),
             ('pepr', 1),
             ('cybersecurite', 20),
             ('est', 1817),
             ('lancé', 12),
             ('france', 732),
             ('permettant', 14),
             ('des', 2817),
             ('transferts', 2),
             ('savoirs', 2),
             ('et', 4470),
             ('technologiques', 19),
             ('entre', 417),
             ('industriels', 14),
             ('universités', 3),
             ('grandes', 60),
             ('écoles', 12),
             ('🕴️💻💶👉https', 1),
             ('wtldk4jao8', 1),
             ('curry', 213),
             ('making', 7637),
             ('48m', 2),
             ('off', 11207),
             ('ring', 664),
             ('mf', 437),
             ('living', 3570),
             ('dream😭😭😭😭', 1),
             ('bn6n5fnpsz', 1),
             ('bowtiedhandyman', 2),
             ('am', 14551),
             ('sinple', 2),
             ('man…truck', 1),
             ('tall', 200),
             ('truck', 893),
             ('loud', 661),
             ('makes', 8750),
             ('thoughts', 1469),
             ('head', 3793),
             ('go', 20282),
             ('away', 6463),
             ('while', 8770),
             ('realhfegelein', 2),
             ('dubbaewwteeeff', 3),
             ('peterdempsey92', 2),
             ('aoc', 1139),
             ('reason', 4932),
             ('europe', 1213),
             ('spend', 1390),
             ('money', 9901),
             ('these', 17449),
             ('low', 2265),

In [30]:
sequences = tokenizer.texts_to_sequences(data['Tweets'])

In [31]:
sequences

[[3347,
  166784,
  272622,
  14945,
  272623,
  362,
  7,
  22,
  386,
  12,
  4,
  197,
  6,
  65,
  233,
  43,
  638,
  296,
  722,
  64,
  3,
  1140,
  3150],
 [100482,
  1079,
  3185,
  166785,
  96,
  20600,
  35066,
  381,
  272624,
  96,
  66,
  2522,
  258,
  12311,
  272625,
  243,
  272626,
  49262,
  10,
  8,
  9,
  272627],
 [10,
  8,
  9,
  272628,
  3742,
  1044,
  9937,
  4,
  281,
  93,
  15,
  5105,
  133,
  208,
  363,
  2159,
  1530],
 [7568,
  7,
  459,
  3,
  2318,
  2,
  14946,
  6,
  883,
  3162,
  996,
  272629,
  29664,
  119,
  99,
  6223,
  4545,
  241,
  58,
  57,
  10,
  8,
  9,
  272630,
  272631,
  272632,
  29664,
  7568],
 [6272,
  11,
  13588,
  80,
  452,
  14784,
  2128,
  2366,
  87,
  3704,
  196,
  272633,
  418,
  123903,
  272634,
  134,
  959,
  4797,
  10908,
  4,
  2122,
  16461,
  272635,
  272636,
  56618,
  272637,
  10,
  8,
  9,
  272638],
 [16,
  2027,
  14,
  48,
  251,
  111,
  2449,
  18,
  2,
  1683,
  4161,
  6,
  172,
  25,
  2,
  4240,
  254,
  33,
  23,
  35,
  23,
  61,
  8312,
  12,
  472,
  1481,
  51,
  560,
  614,
  780,
  8184,
  43,
  421,
  9167,
  701,
  7,
  41,
  3524,
  2,
  382,
  2253,
  6,
  4,
  622,
  20,
  40,
  100483,
  2537],
 [243,
  7647,
  272639,
  4,
  272640,
  4,
  13448,
  26522,
  1338,
  41778,
  25263,
  4043,
  647,
  43942,
  738,
  4,
  13448,
  26522,
  647,
  272641,
  272642,
  272643,
  4,
  275,
  103,
  28003,
  713,
  49263,
  6080,
  738,
  310,
  272644,
  26522,
  272645,
  96,
  67289,
  272646,
  272647],
 [472,
  299,
  3200,
  560,
  12843,
  5106,
  2,
  6686,
  5,
  27,
  2450,
  110,
  2558,
  9489,
  69,
  368,
  34,
  2,
  559,
  50,
  20,
  13069,
  1730,
  51,
  174,
  2041,
  4334,
  50,
  112,
  88,
  167,
  3,
  190,
  157,
  69,
  22,
  40,
  103],
 [67290,
  4,
  94,
  18334,
  47,
  43943,
  4,
  9224,
  43,
  808,
  3,
  4,
  10153,
  9224,
  249,
  122,
  955,
  46448,
  106,
  36,
  4,
  602,
  56,
  16,
  3516],
 [166786,
  166787,
  12959,
  11,
  406,
  69,
  4,
  89,
  1037,
  14,
  4,
  665,
  5,
  155,
  5311,
  50,
  11,
  12960,
  63,
  406,
  15,
  8616,
  51,
  1260,
  7,
  724,
  12,
  164,
  887,
  25,
  69,
  4,
  42,
  1041,
  244,
  112,
  2254,
  51,
  886,
  43,
  112,
  285,
  20,
  1025,
  7,
  998,
  1284,
  15,
  656,
  15495,
  25,
  11898,
  313],
 [6687,
  17565,
  1336,
  67291,
  28,
  108,
  24,
  7156,
  33,
  35,
  88,
  710,
  7,
  35067,
  64,
  61,
  611,
  5,
  1421,
  1031,
  21,
  1312,
  3,
  293,
  12529,
  1017,
  1591,
  3,
  1060,
  2151,
  710],
 [1638,
  3834,
  17329,
  9439,
  17330,
  1119,
  166788,
  15862,
  136,
  4253,
  2255,
  20601,
  10,
  8,
  9,
  272648,
  42,
  4395,
  30569,
  17329,
  7,
  35,
  588,
  414,
  85499,
  22],
 [7,
  38149,
  4,
  176,
  30,
  26,
  1005,
  80,
  5,
  67,
  3346,
  12,
  79,
  6782,
  5,
  272649,
  5,
  23483,
  5,
  67292,
  16462,
  272650,
  10614,
  10,
  8,
  9,
  272651],
 [272652,
  59,
  2,
  157,
  507,
  6,
  9871,
  528,
  74974,
  2131,
  25865,
  53,
  504,
  41,
  4,
  6661,
  5867,
  237,
  8266,
  16,
  63,
  4326,
  4564,
  3,
  53,
  135,
  2112,
  30,
  32,
  113,
  3,
  87,
  17,
  2370,
  2160,
  3106,
  5,
  154,
  1683,
  5,
  2,
  166789,
  63,
  23,
  40,
  7859,
  90,
  6574],
 [272653,
  272654,
  19555,
  6549,
  35068,
  11,
  2021,
  3,
  77,
  74,
  826,
  14,
  4,
  1037,
  331,
  75,
  200,
  20,
  8347,
  478,
  1039,
  174,
  168],
 [2881,
  334,
  146,
  18,
  272655,
  1373,
  4694,
  12,
  272656,
  948,
  3647,
  1768,
  1844,
  2137,
  364,
  3828,
  1249,
  103,
  41779,
  52654,
  1064,
  67293,
  85500],
 [34,
  2,
  276,
  33,
  8424,
  10075,
  1472,
  3,
  897,
  77,
  26,
  15,
  797,
  850,
  1407,
  11,
  152,
  674,
  1324,
  144,
  31505,
  61,
  5920,
  31,
  122,
  31,
  61,
  2241,
  26,
  2030,
  64,
  489,
  292,
  12530,
  28,
  13304,
  297,
  11,
  127,
  23,
  339,
  207,
  45,
  2,
  186,
  13188,
  10,
  8,
  9,
  272657],
 [272658,
  3037,
  10154,
  1176,
  4140,
  22,
  376,
  2612,
  12,
  272659,
  100484,
  100485,
  6100,
  11642,
  568,
  14,
  3221,
  56619,
  256,
  84,
  2015,
  56620,
  50,
  20230,
  92,
  154,
  272660,
  45,
  804,
  1695,
  166790,
  3978,
  1408,
  28004,
  166791],
 [367, 14022, 13, 76, 175, 32, 1139, 240, 411, 45, 13],
 [52655,
  46,
  2,
  124,
  69,
  138,
  125,
  1055,
  3,
  289,
  2,
  539,
  1773,
  1462,
  2,
  2570,
  24,
  86,
  2,
  9118,
  156,
  225,
  5,
  22,
  100486,
  695,
  151,
  40,
  506,
  208],
 [17822, 3852, 4162, 17, 7, 416, 86, 36, 644],
 [50, 959, 55, 42, 166792, 7, 59, 318, 330, 114],
 [1047,
  5149,
  225,
  7,
  170,
  106,
  79,
  771,
  4935,
  2217,
  1514,
  455,
  6832,
  1595,
  11358,
  10,
  8,
  9,
  272661],
 [69,
  29,
  634,
  3,
  829,
  2,
  482,
  44,
  2,
  4537,
  16050,
  51,
  24680,
  1755,
  5722,
  18335,
  52656,
  273,
  5,
  5004,
  1214,
  273,
  14,
  33746,
  73,
  304,
  10,
  8,
  9,
  272662],
 [3772,
  28796,
  32,
  2045,
  752,
  46,
  14947,
  2,
  1568,
  69,
  4,
  778,
  108,
  544,
  14,
  4,
  1414,
  6,
  2,
  1428,
  27,
  2517,
  3,
  273,
  5,
  1635,
  70,
  579,
  26,
  232,
  148,
  106,
  4,
  41780,
  214,
  7,
  2,
  179,
  31,
  272,
  669,
  37,
  32,
  74975,
  860,
  51,
  14785,
  53,
  8663],
 [1207,
  143,
  7,
  272663,
  980,
  104,
  30,
  128,
  795,
  1256,
  4,
  7096,
  136,
  606,
  17,
  2640,
  168,
  298,
  562,
  395,
  274,
  86,
  2670,
  17566,
  1644],
 [123904, 739, 32532, 7, 202, 94, 154, 1869],
 [272664,
  272665,
  11,
  36,
  4114,
  3,
  28,
  157,
  551,
  253,
  46,
  272666,
  126,
  8517,
  44,
  2,
  179,
  100,
  126,
  18642,
  272667,
  31,
  272668,
  5383,
  264,
  11,
  141,
  104,
  864,
  17331,
  14,
  29665,
  118,
  2930],
 [103,
  12,
  123905,
  18,
  5683,
  7648,
  2822,
  100487,
  1144,
  357,
  85501,
  725,
  5,
  74976,
  1144,
  545,
  10,
  8,
  9,
  20231],
 [16659,
  37,
  85502,
  704,
  7067,
  61295,
  895,
  16237,
  258,
  12531,
  96,
  6341,
  272669,
  1948,
  811,
  8267,
  258,
  1336,
  123906,
  707,
  123907,
  1079,
  3419,
  707,
  4829,
  160,
  123908,
  4936,
  788,
  10155,
  73,
  160,
  310,
  9,
  23484,
  29666,
  5150,
  617,
  85503,
  384,
  165,
  31506,
  747,
  874,
  166793,
  26523,
  2125,
  13189],
 [99,
  1530,
  74977,
  85504,
  378,
  272670,
  32533,
  1038,
  46449,
  243,
  2355,
  41781,
  672,
  166794,
  96,
  166795,
  428,
  33747,
  3705,
  41782,
  123909,
  428,
  15309,
  46450,
  272671,
  8,
  9,
  272672],
 [6224,
  267,
  166796,
  368,
  187,
  4,
  2545,
  17,
  3584,
  533,
  28,
  272673,
  10,
  8,
  9,
  272674],
 [166797,
  162,
  166798,
  272675,
  7,
  6530,
  1989,
  7,
  2556,
  1989,
  231,
  2,
  66,
  1288,
  12,
  499,
  123,
  311,
  14,
  4,
  229],
 [166799,
  123910,
  166800,
  1600,
  2,
  393,
  1523,
  47,
  1364,
  203,
  18,
  142,
  848,
  662,
  2571,
  7,
  95,
  33,
  112,
  1364,
  18,
  3355,
  5,
  33,
  112,
  1364,
  18,
  99,
  150,
  4988,
  1745,
  184,
  35,
  15,
  528,
  44,
  555],
 [11813,
  1049,
  2356,
  615,
  3,
  2,
  52,
  11,
  141,
  138,
  2504,
  2,
  6662,
  1381,
  28,
  373,
  410,
  3,
  2,
  52,
  62,
  54,
  91,
  171,
  71,
  14,
  48,
  2,
  52,
  15,
  770,
  272676,
  2,
  79,
  702,
  6,
  48,
  37,
  637,
  141,
  188,
  19,
  306,
  3,
  274,
  55,
  122,
  11,
  152,
  123911,
  272677],
 [11,
  139,
  17,
  1690,
  169,
  5,
  12739,
  11,
  199,
  41,
  83,
  144,
  3,
  19,
  66,
  10,
  8,
  9,
  272678],
 [166801,
  11179,
  878,
  35069,
  6273,
  1240,
  272679,
  1389,
  1090,
  33748,
  1074,
  5621,
  957,
  166802,
  9733,
  7340,
  39888,
  902,
  294,
  75,
  574,
  11180,
  19238,
  2388,
  272680,
  6129,
  61296,
  272681,
  56621],
 [272682,
  85505,
  123912,
  4100,
  36,
  6246,
  29667,
  2581,
  284,
  38,
  11,
  398,
  3,
  3037,
  1644,
  11,
  1316,
  41,
  268,
  78,
  145,
  16,
  3309],
 [1008,
  4,
  373,
  623,
  4471,
  18,
  35,
  2,
  254,
  12,
  28,
  371,
  5,
  577,
  1243,
  95,
  2,
  371,
  2375,
  225,
  232,
  3,
  84,
  61,
  614,
  34,
  35,
  30,
  27,
  703,
  49,
  16,
  11,
  291,
  31,
  156,
  49],
 [589,
  133,
  157,
  87,
  793,
  130,
  222,
  755,
  550,
  302,
  297,
  13,
  680,
  296,
  19,
  1495],
 [5, 111, 78, 31, 669, 10, 8, 9, 272683],
 [35070,
  52657,
  1212,
  1018,
  43944,
  19239,
  23,
  91,
  836,
  417,
  12,
  35070,
  52657,
  1168,
  3,
  938,
  65,
  950,
  10,
  8,
  9,
  272684],
 [31507,
  3,
  3867,
  99,
  1131,
  18,
  1012,
  1463,
  3437,
  37,
  6,
  3548,
  2494,
  1926,
  879,
  5684,
  9225,
  3779,
  31,
  40,
  2854,
  597,
  123913,
  54,
  91,
  1127,
  3799,
  1609,
  2,
  166803,
  23485,
  28797,
  34,
  935,
  558,
  123914,
  10,
  8,
  9,
  272685],
 [5942,
  46451,
  6204,
  589,
  4970,
  1019,
  4,
  81,
  4170,
  54,
  37,
  1546,
  118,
  18,
  4,
  3402,
  470],
 [74978,
  123915,
  4,
  41783,
  2694,
  46452,
  33749,
  195,
  280,
  1008,
  29,
  684,
  6,
  2,
  67294,
  4,
  41784,
  357,
  2074,
  5,
  4044,
  541,
  12,
  4360,
  5,
  4918,
  136,
  2,
  762,
  1184,
  136,
  2,
  12844,
  6,
  4,
  3156,
  6886,
  13305,
  7,
  4,
  41785,
  5,
  7,
  4,
  365,
  81,
  14,
  2482,
  1479],
 [132, 10, 8, 9, 272686],
 [17131,
  21,
  13,
  75,
  13,
  21,
  125,
  122,
  4,
  13306,
  3,
  19,
  1011,
  48,
  294,
  294,
  2,
  49264,
  21,
  15,
  124,
  3100,
  10,
  8,
  9,
  272687],
 [19240,
  6,
  20602,
  921,
  8245,
  56622,
  1818,
  26524,
  18082,
  9872,
  17823,
  166804,
  28,
  915,
  349,
  379,
  48,
  15,
  105,
  2,
  157,
  82,
  147,
  24,
  2982,
  106,
  2,
  100488,
  3979],
 [272688,
  256,
  158,
  240,
  6,
  440,
  5,
  15,
  1035,
  6,
  1367,
  56623,
  21,
  166805,
  508,
  782,
  6,
  13,
  5,
  2,
  681,
  8215,
  198,
  14,
  4349,
  35,
  6,
  17,
  537,
  247,
  2570,
  5,
  3371,
  173,
  17,
  389,
  26,
  815,
  3,
  19,
  147,
  3,
  87,
  16,
  35,
  14634],
 [997, 39, 138, 1241, 74979, 272689, 7, 2, 344],
 [166806,
  272690,
  594,
  1091,
  21341,
  243,
  108,
  1401,
  12845,
  830,
  61297,
  866,
  378,
  1614],
 [272691,
  43945,
  272692,
  3,
  1060,
  23486,
  107,
  21342,
  22,
  2211,
  147,
  1669,
  10457,
  4,
  7031,
  255,
  790,
  136,
  118,
  6081,
  46,
  2,
  3201,
  51,
  10390,
  6,
  2,
  1080,
  1966,
  2,
  93,
  6,
  16238,
  849,
  11181,
  28798,
  211,
  627,
  1272,
  33750,
  46,
  2,
  18083,
  4123,
  27280,
  27281,
  10,
  8,
  9,
  272693],
 [61298,
  5323,
  2,
  76,
  401,
  262,
  110,
  289,
  13,
  38,
  1343,
  10909,
  202,
  375,
  41,
  12624,
  28,
  3829,
  3953,
  5,
  5151,
  63,
  41,
  4,
  100489],
 [36,
  1487,
  169,
  22,
  52,
  6,
  2,
  498,
  2078,
  2195,
  982,
  113,
  4437,
  12,
  2,
  186,
  1199,
  163,
  2,
  10220,
  7,
  2281,
  99,
  2649,
  5,
  806,
  21,
  109,
  446,
  12,
  555,
  8035,
  54,
  173,
  1523,
  40,
  881,
  7188,
  37,
  1180,
  37,
  200],
 [67295,
  1289,
  23,
  173,
  4,
  72,
  729,
  3,
  6012,
  9440,
  53,
  365,
  39,
  74,
  19,
  357,
  3107,
  43,
  1289],
 [272694,
  697,
  2,
  2415,
  3960,
  7,
  2749,
  25,
  2,
  123916,
  123917,
  292,
  161,
  5,
  7,
  1261,
  89,
  2,
  997,
  216,
  7,
  8805,
  2,
  569,
  6,
  2,
  189,
  3128,
  15],
 [272695,
  272696,
  100490,
  272697,
  60,
  15863,
  1730,
  20,
  4,
  10996,
  1524,
  34,
  4,
  500,
  4145,
  186,
  1340,
  316],
 [2,
  4590,
  6,
  4598,
  2641,
  1998,
  3,
  2935,
  12,
  3284,
  587,
  106,
  1794,
  61299,
  1655,
  342,
  74,
  453,
  1540,
  74,
  34,
  10,
  8,
  9,
  272698,
  272699,
  4546,
  2494,
  99,
  3284,
  526,
  25866,
  61300],
 [166807,
  100491,
  52658,
  60,
  166808,
  12,
  2,
  205,
  5,
  46453,
  20,
  60,
  33751,
  5,
  74980,
  12,
  2,
  205],
 [5,
  71,
  21,
  358,
  167,
  174,
  7526,
  852,
  41,
  27,
  598,
  120,
  4599,
  9168,
  5,
  11182,
  26,
  256,
  256,
  598,
  235,
  467,
  1119,
  98,
  32,
  127,
  22532,
  1784,
  5,
  2,
  7371,
  5,
  105,
  12421,
  18,
  22994,
  74981,
  32,
  2581,
  1092,
  125,
  5508,
  127,
  192,
  68,
  26,
  246],
 [8518,
  1219,
  142,
  238,
  50,
  117,
  19,
  3616,
  22,
  46,
  2722,
  65,
  25,
  12,
  2,
  179,
  124,
  5384,
  937,
  4666,
  77,
  372,
  4361,
  37,
  4971,
  117,
  19,
  717,
  37,
  73,
  1712,
  117,
  19,
  585,
  2722,
  65,
  109,
  235,
  7569,
  3,
  234,
  50],
 [74982,
  488,
  272700,
  604,
  307,
  1248,
  5243,
  57,
  272701,
  46454,
  3204,
  84,
  1427,
  2958,
  5,
  155,
  57,
  10,
  8,
  9,
  272702],
 [171,
  329,
  440,
  2,
  212,
  59,
  2,
  114,
  2948,
  2,
  362,
  585,
  222,
  755,
  101,
  6988,
  27,
  235,
  128,
  59,
  35,
  2,
  50,
  21,
  143,
  21,
  457,
  62,
  7,
  314,
  15,
  323,
  1308,
  32,
  7,
  855,
  58,
  6,
  50,
  1312,
  3,
  777,
  2274],
 [38, 7, 68, 20, 67296, 10, 8, 9, 272703],
 [37,
  3009,
  6,
  2,
  272704,
  38150,
  27282,
  28,
  1602,
  6735,
  349,
  195,
  137,
  2,
  41786,
  6,
  207],
 [10221,
  1386,
  701,
  99,
  1012,
  7212,
  3942,
  55,
  3,
  272705,
  346,
  10,
  8,
  9,
  272706,
  10,
  8,
  9,
  272707],
 [74983,
  2,
  1956,
  323,
  192,
  45,
  5364,
  43,
  4770,
  23487,
  61,
  818,
  1967,
  12,
  2898,
  20,
  3756,
  43,
  34,
  154,
  25867,
  16,
  780,
  10538,
  3,
  2719,
  65,
  5,
  726,
  5230,
  3403,
  101,
  2,
  8979,
  2002,
  272708],
 [20603,
  12,
  2501,
  20,
  20603,
  16051,
  5,
  935,
  99,
  51,
  3284,
  597,
  1703,
  2,
  1987,
  6,
  2,
  10615,
  4499,
  51,
  864,
  1262,
  12,
  1002,
  10615,
  937,
  20603,
  4499,
  864,
  10615,
  272709,
  272710,
  526,
  10,
  8,
  9,
  272711],
 [2,
  365,
  11997,
  2725,
  82,
  718,
  338,
  18,
  74984,
  20,
  2,
  15864,
  2528,
  46,
  18336,
  5,
  61301,
  10,
  8,
  9,
  272712],
 [1451,
  321,
  328,
  57,
  99,
  33,
  296,
  19,
  627,
  2282,
  174,
  149,
  385,
  613,
  74985,
  14,
  218,
  42,
  161,
  10,
  8,
  9,
  272713],
 [55, 21, 13, 4, 66, 621, 3108, 24037, 28005, 272714, 272715],
 [272716,
  1029,
  55,
  21,
  13,
  444,
  70,
  2117,
  1173,
  20,
  40,
  103,
  169,
  74,
  55,
  49,
  33,
  13,
  88,
  30,
  2,
  499,
  6,
  2,
  2117,
  7,
  12,
  2,
  114,
  5921],
 [7213, 3, 1598, 208, 363, 12, 82, 20, 9169, 597, 10, 8, 9, 272717],
 [7245,
  7499,
  3780,
  2,
  901,
  6,
  50,
  21,
  2314,
  20,
  2,
  147,
  5,
  74,
  95,
  50,
  21,
  2362,
  147,
  5,
  74,
  15,
  3395,
  274,
  7,
  5741,
  27,
  242,
  1703,
  71,
  39,
  19,
  37,
  81,
  10391],
 [56624, 375, 41, 40, 4311, 6, 81, 1780, 211, 52, 6, 1367, 10, 8, 9, 272718],
 [6755, 67, 1923, 16, 64, 15, 39, 759, 137, 228, 33752, 82, 13858],
 [42, 46, 316, 272719, 272720],
 [166809,
  123918,
  21,
  164,
  62,
  21,
  3038,
  4362,
  74,
  27,
  512,
  2,
  1251,
  20,
  2,
  4756,
  6,
  3524,
  38,
  24,
  8567,
  31,
  94,
  25,
  136,
  43946,
  192,
  7,
  1477,
  31,
  4,
  507,
  6,
  3524],
 [166810,
  27283,
  13070,
  7,
  36,
  4,
  11541,
  33753,
  4811,
  3,
  382,
  6,
  2155,
  6858,
  1841,
  6,
  513,
  13,
  47,
  293,
  20,
  29,
  5365,
  376,
  18,
  382,
  6,
  13070,
  14,
  82],
 [39889,
  2695,
  4919,
  17824,
  101,
  7,
  16,
  26,
  300,
  3,
  235,
  2,
  452,
  6,
  4,
  366,
  81],
 [21716, 36569, 100, 7, 27284, 39, 109, 123, 5, 5280, 16, 15310, 272721],
 [49265,
  266,
  35,
  159,
  5742,
  537,
  14635,
  439,
  46,
  439,
  7,
  4,
  57,
  1557,
  5,
  630,
  327,
  1569,
  1207,
  26,
  31,
  3,
  151,
  2,
  272722,
  2,
  12625,
  33754,
  52659,
  51,
  35,
  164,
  62,
  3675,
  7,
  2,
  1067,
  6,
  1913,
  82,
  687,
  252,
  3,
  809,
  4,
  365,
  12,
  150,
  687,
  35,
  883],
 [272723,
  3829,
  2968,
  4,
  671,
  1120,
  3,
  35071,
  5,
  3654,
  33,
  39,
  683,
  13,
  26,
  122,
  9275,
  263,
  13,
  14,
  35,
  2,
  430,
  161,
  13,
  23,
  225,
  123919,
  2,
  1253,
  6,
  29,
  11457,
  1234,
  13,
  39,
  19,
  234,
  40,
  86,
  33755,
  272724],
 [589,
  66,
  73,
  158,
  2197,
  211,
  1020,
  234,
  31,
  33,
  21,
  144,
  3,
  56,
  1531,
  20,
  174,
  536,
  10997,
  21,
  2247,
  5107,
  31,
  22,
  494,
  17,
  7,
  38,
  781,
  59,
  4,
  2272,
  2396,
  1454,
  1448,
  17332,
  3638,
  3,
  2069,
  2,
  65,
  1089,
  1019,
  10,
  8,
  9,
  272725],
 [640,
  3,
  80,
  637,
  17,
  395,
  36,
  2052,
  15,
  143,
  279,
  36,
  949,
  14,
  25,
  4341,
  2,
  2316,
  1449,
  44,
  2,
  146,
  2183,
  229,
  16,
  24,
  1328,
  62,
  7,
  757,
  306,
  3,
  245,
  17,
  265,
  360,
  11,
  493,
  33,
  88,
  2,
  344,
  3,
  15,
  108,
  1858,
  10,
  8,
  9,
  272726],
 [259,
  11359,
  3,
  319,
  235,
  1666,
  3,
  5,
  486,
  60,
  1247,
  15,
  730,
  55,
  49,
  33,
  626,
  3,
  84,
  38,
  33,
  49,
  13,
  129,
  1169,
  14,
  50,
  3,
  803,
  19556,
  13,
  451,
  939,
  8762,
  1756,
  59,
  19556,
  528,
  3,
  140,
  12,
  1247,
  130],
 [2, 50, 23, 4627, 5, 2, 50, 21, 68, 10, 8, 9, 272727],
 [10774, 331, 138, 417, 4, 41787, 682, 11, 4058, 2, 68, 3749, 504],
 [117,
  191,
  289,
  143,
  15,
  87,
  380,
  7,
  4,
  536,
  38,
  45,
  1581,
  6,
  4,
  361,
  1748,
  74986,
  143,
  2274,
  4249],
 [272728,
  5582,
  166811,
  67297,
  111,
  272,
  15,
  13,
  47,
  121,
  226,
  215,
  31,
  4,
  1042,
  6,
  1009,
  456,
  95,
  6,
  2,
  233,
  13,
  260,
  12,
  26,
  13,
  47,
  626,
  3,
  102,
  76,
  542,
  5,
  22,
  23,
  3,
  1615,
  45,
  16],
 [123920,
  272729,
  11,
  911,
  240,
  45,
  380,
  97,
  2,
  5531,
  22,
  1919,
  4610,
  46,
  2,
  1033,
  18,
  2,
  272730,
  447,
  122,
  85,
  3,
  8763,
  251,
  27,
  882,
  2,
  3617,
  6,
  513,
  179,
  831,
  117,
  1225,
  3,
  247],
 [76, 3347, 272731],
 [6101, 345, 15, 5670, 40, 1748, 6, 2, 65],
 [272732,
  17567,
  22,
  3661,
  734,
  80,
  194,
  38,
  67,
  153,
  11,
  23,
  388,
  2134,
  11,
  92,
  247,
  7,
  19,
  3013,
  6,
  267,
  164,
  1124,
  28,
  1187,
  7,
  36,
  4,
  1680,
  1916,
  150,
  7,
  85506,
  5,
  4,
  485,
  2489,
  2518,
  2,
  281,
  10,
  8,
  9,
  272733,
  11,
  24,
  68,
  18,
  2,
  168,
  377],
 [55, 46455, 3549, 7, 6612, 1687, 1582, 99, 10, 8, 9, 272734],
 [2190,
  25,
  1005,
  126,
  1043,
  6370,
  10076,
  557,
  7,
  300,
  14,
  48,
  83,
  4,
  277,
  85,
  12,
  1136,
  106,
  12,
  28,
  915,
  6965,
  14,
  107,
  393,
  10,
  8,
  9,
  272735],
 [180, 2, 660, 197, 131, 245, 12, 2, 748, 6, 65],
 [3,
  35,
  18643,
  2892,
  256,
  88,
  17,
  324,
  7,
  4,
  204,
  388,
  2,
  1697,
  100492,
  32,
  7246,
  22,
  7900,
  311,
  44,
  1721,
  212,
  282,
  22,
  4,
  6102,
  5,
  39,
  213,
  64,
  3,
  53,
  2218,
  32,
  4,
  1721,
  298,
  889,
  5,
  32,
  728,
  23488,
  27,
  5263,
  5,
  173,
  98,
  4,
  35,
  756,
  32,
  39,
  235,
  18643,
  2,
  179,
  1728,
  10,
  8,
  9,
  272736],
 [906,
  10539,
  6756,
  272737,
  7649,
  11643,
  99,
  2671,
  34,
  272738,
  10,
  8,
  9,
  272739,
  10,
  8,
  9,
  272740],
 [272741,
  272742,
  55,
  3483,
  3,
  102,
  17,
  966,
  5,
  116,
  2391,
  220,
  447,
  20,
  191,
  14786,
  20,
  13,
  6318,
  272743,
  55,
  3483,
  3,
  161,
  14,
  2,
  143,
  366,
  383,
  12,
  2,
  157,
  338,
  262,
  890,
  276,
  64,
  4,
  756,
  87,
  12,
  40,
  1560,
  1153,
  10910,
  7311],
 [16052,
  6415,
  79,
  166812,
  272744,
  16052,
  15126,
  43947,
  166812,
  272745,
  16052,
  272746,
  272747,
  17333,
  64,
  14,
  2,
  15865,
  7783,
  6,
  2,
  616,
  2823,
  46,
  8,
  992,
  15127,
  7,
  58,
  74,
  12,
  17825,
  10,
  8,
  9,
  272748,
  10,
  8,
  9,
  272749],
 [327,
  42,
  54,
  192,
  3,
  49,
  20,
  15311,
  13,
  47,
  19,
  1209,
  5,
  121,
  190,
  42,
  3151,
  28799,
  10,
  8,
  9,
  272750],
 [272751,
  10285,
  193,
  18,
  2,
  76,
  298,
  324,
  54,
  2088,
  10540,
  32,
  2043,
  35,
  6,
  2,
  189,
  17,
  369,
  14,
  4,
  223,
  90,
  980,
  35,
  235,
  98,
  4,
  602,
  51,
  19,
  550,
  3,
  98,
  166813],

In [32]:
len((sequences[0]))

23

In [33]:
len((sequences[1]))

22

In [34]:
len((sequences[2]))

17

In [35]:
from keras.utils import pad_sequences

### Padding the sequences :
- When we convert text into sequence of numbers, we get sequences of different lengths.
- But for training a model, we need all the sequences to be of the same length.
- So we use padding to make all the sequences of the same length.
- pad as pre or post. 
- If we pad as pre, then we add zeros at the beginning of the sequence.
- If we pad as post, then we add zeros at the end of the sequence.

In [36]:
sequences = pad_sequences(sequences, padding='pre')

In [37]:
sequences

array([[      0,       0,       0, ...,       3,    1140,    3150],
       [      0,       0,       0, ...,       8,       9,  272627],
       [      0,       0,       0, ...,     363,    2159,    1530],
       ...,
       [      0,       0,       0, ..., 1052348,   59425,     906],
       [      0,       0,       0, ...,     646,      91,      86],
       [      0,       0,       0, ...,     111,     446,      25]],
      dtype=int32)

### Text --> [Integer Sequence] --> [Padded Integer Sequence] --> Model

In [38]:
# # Disable GPU for this notebook
# import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

# import tensorflow as tf
# try:
#     tf.config.set_visible_devices([], "GPU")
# except RuntimeError:
#     # Happens if TF already initialized GPU; restart kernel and run from top
#     pass

# print("GPUs visible to TensorFlow:", tf.config.list_physical_devices("GPU"))

# Correct imports (avoid standalone keras import warning)
from keras.layers import SimpleRNN, Embedding, Dense, Input, Dropout
from keras.models import Sequential

In [39]:
X = sequences

In [40]:
y = data['Sentiment'].values

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [43]:
x_train.shape

(581162, 120)

### Embedding Layer :
- It is used to convert the integer sequences into dense vectors of fixed size.
- After including the embedding layer, we capture the semantic meaning of the words in the text.

### Vocab Size :
- It is the total number of unique words in the text.
- It is calculated as the length of the word index created by the tokenizer + 1 (to account for the OOV token).

In [44]:
vocab_size = len(tokenizer.word_index) + 1

In [45]:
x_train.shape[1:]

(120,)

In [46]:
model_final = Sequential([
    Input(shape=(x_train.shape[1],)),

    Embedding(input_dim=vocab_size, output_dim=32, mask_zero=True),

    SimpleRNN(64, dropout=0.2),

    Dense(16, activation='relu'),
    Dropout(0.3),

    Dense(3, activation='softmax')
])

I0000 00:00:1777177004.637506   27274 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1246 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 6GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

In [47]:
model_final.compile(optimizer='adam', 
                    loss='sparse_categorical_crossentropy', 
                    metrics=['accuracy']
                    )

In [48]:
model_final.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 120, 32)        │    33,675,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 64)             │         6,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 33,682,467 (128.49 MB)

 Trainable params: 33,682,467 (128.49 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model_final.fit(x_train, y_train, epochs=100, validation_data=(x_test, y_test), batch_size=64)

Epoch 1/100

I0000 00:00:1777177008.070316   27404 service.cc:148] XLA service 0x79595401c240 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1777177008.070349   27404 service.cc:156]   StreamExecutor device (0): NVIDIA GeForce RTX 3050 6GB Laptop GPU, Compute Capability 8.6
2026-04-26 09:46:48.130720: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1777177008.320110   27404 cuda_dnn.cc:529] Loaded cuDNN version 91700

   5/9081 ━━━━━━━━━━━━━━━━━━━━ 4:16 28ms/step - accuracy: 0.3214 - loss: 1.1097

I0000 00:00:1777177010.521754   27404 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

9081/9081 ━━━━━━━━━━━━━━━━━━━━ 245s 26ms/step - accuracy: 0.8857 - loss: 0.2995 - val_accuracy: 0.8022 - val_loss: 0.4746
Epoch 2/100
1296/9081 ━━━━━━━━━━━━━━━━━━━━ 4:47 37ms/step - accuracy: 0.8719 - loss: 0.3577

In [ ]:
import pickle

In [ ]:
with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)

In [ ]:
# model_final.save('sentiment_analysis_model.h5')
model_final.save('sentiment_analysis_model.keras')